import { Suggestion } from '../types'

export const SUGGESTION_POOL: Suggestion[] = [
  {
    id: 'career-job-work-satisfaction-s1',
    factorId: 'career-job-work-satisfaction',
    title: 'Job / work satisfaction',
    description: 'Identify one task that would improve your day.',
    impact: 77,
    category: 'ideal-gap',
  },
  {
    id: 'career-job-work-satisfaction-s2',
    factorId: 'career-job-work-satisfaction',
    title: 'Job / work satisfaction',
    description: 'Improve your workspace setup.',
    impact: 74,
    category: 'ideal-gap',
  },
  {
    id: 'career-job-work-satisfaction-s3',
    factorId: 'career-job-work-satisfaction',
    title: 'Job / work satisfaction',
    description: 'Ask a colleague for feedback.',
    impact: 68,
    category: 'ideal-gap',
  },
  {
    id: 'career-job-work-satisfaction-s4',
    factorId: 'career-job-work-satisfaction',
    title: 'Job / work satisfaction',
    description: 'Block focused work time.',
    impact: 65,
    category: 'ideal-gap',
  },
  {
    id: 'career-job-work-satisfaction-s5',
    factorId: 'career-job-work-satisfaction',
    title: 'Job / work satisfaction',
    description: 'Remove one distraction.',
    impact: 74,
    category: 'ideal-gap',
  },
  {
    id: 'career-job-work-satisfaction-s6',
    factorId: 'career-job-work-satisfaction',
    title: 'Job / work satisfaction',
    description: 'Reflect on what you enjoy at work.',
    impact: 69,
    category: 'ideal-gap',
  },
  {
    id: 'career-job-work-satisfaction-s7',
    factorId: 'career-job-work-satisfaction',
    title: 'Job / work satisfaction',
    description: 'Write one improvement idea for your role.',
    impact: 73,
    category: 'ideal-gap',
  },
  {
    id: 'career-job-work-satisfaction-s8',
    factorId: 'career-job-work-satisfaction',
    title: 'Job / work satisfaction',
    description: 'Have a short conversation with a coworker.',
    impact: 69,
    category: 'ideal-gap',
  },
  {
    id: 'career-job-work-satisfaction-s9',
    factorId: 'career-job-work-satisfaction',
    title: 'Job / work satisfaction',
    description: 'Clarify priorities for the week.',
    impact: 72,
    category: 'ideal-gap',
  },
  {
    id: 'career-job-work-satisfaction-s10',
    factorId: 'career-job-work-satisfaction',
    title: 'Job / work satisfaction',
    description: 'Celebrate finishing a hard task.',
    impact: 69,
    category: 'ideal-gap',
  },
  {
    id: 'career-personal-projects-s1',
    factorId: 'career-personal-projects',
    title: 'Personal projects',
    description: 'Work 30 minutes on a personal project.',
    impact: 64,
    category: 'ideal-gap',
  },
  {
    id: 'career-personal-projects-s2',
    factorId: 'career-personal-projects',
    title: 'Personal projects',
    description: 'Write the next step for your project.',
    impact: 65,
    category: 'ideal-gap',
  },
  {
    id: 'career-personal-projects-s3',
    factorId: 'career-personal-projects',
    title: 'Personal projects',
    description: 'Share your project idea with someone.',
    impact: 67,
    category: 'ideal-gap',
  },
  {
    id: 'career-personal-projects-s4',
    factorId: 'career-personal-projects',
    title: 'Personal projects',
    description: 'Research something related to the project.',
    impact: 64,
    category: 'ideal-gap',
  },
  {
    id: 'career-personal-projects-s5',
    factorId: 'career-personal-projects',
    title: 'Personal projects',
    description: 'Organize project materials.',
    impact: 65,
    category: 'ideal-gap',
  },
  {
    id: 'career-personal-projects-s6',
    factorId: 'career-personal-projects',
    title: 'Personal projects',
    description: 'Schedule weekly time for it.',
    impact: 73,
    category: 'ideal-gap',
  },
  {
    id: 'career-personal-projects-s7',
    factorId: 'career-personal-projects',
    title: 'Personal projects',
    description: 'Define a milestone for the week.',
    impact: 73,
    category: 'ideal-gap',
  },
  {
    id: 'career-personal-projects-s8',
    factorId: 'career-personal-projects',
    title: 'Personal projects',
    description: 'Sketch or outline your idea.',
    impact: 65,
    category: 'ideal-gap',
  },
  {
    id: 'career-personal-projects-s9',
    factorId: 'career-personal-projects',
    title: 'Personal projects',
    description: 'Review progress you\'ve made.',
    impact: 68,
    category: 'ideal-gap',
  },
  {
    id: 'career-personal-projects-s10',
    factorId: 'career-personal-projects',
    title: 'Personal projects',
    description: 'Work on it for just 15 focused minutes.',
    impact: 67,
    category: 'ideal-gap',
  },
  {
    id: 'career-sense-of-purpose-s1',
    factorId: 'career-sense-of-purpose',
    title: 'Sense of purpose',
    description: 'Write down what matters most to you.',
    impact: 65,
    category: 'ideal-gap',
  },
  {
    id: 'career-sense-of-purpose-s2',
    factorId: 'career-sense-of-purpose',
    title: 'Sense of purpose',
    description: 'Reflect on how your work helps others.',
    impact: 71,
    category: 'ideal-gap',
  },
  {
    id: 'career-sense-of-purpose-s3',
    factorId: 'career-sense-of-purpose',
    title: 'Sense of purpose',
    description: 'Set a meaningful goal for the month.',
    impact: 73,
    category: 'ideal-gap',
  },
  {
    id: 'career-sense-of-purpose-s4',
    factorId: 'career-sense-of-purpose',
    title: 'Sense of purpose',
    description: 'Write a short mission statement.',
    impact: 77,
    category: 'ideal-gap',
  },
  {
    id: 'career-sense-of-purpose-s5',
    factorId: 'career-sense-of-purpose',
    title: 'Sense of purpose',
    description: 'Think about a problem you\'d like to solve.',
    impact: 66,
    category: 'ideal-gap',
  },
  {
    id: 'career-sense-of-purpose-s6',
    factorId: 'career-sense-of-purpose',
    title: 'Sense of purpose',
    description: 'Help someone with your skills.',
    impact: 64,
    category: 'ideal-gap',
  },
  {
    id: 'career-sense-of-purpose-s7',
    factorId: 'career-sense-of-purpose',
    title: 'Sense of purpose',
    description: 'Volunteer time or expertise.',
    impact: 73,
    category: 'ideal-gap',
  },
  {
    id: 'career-sense-of-purpose-s8',
    factorId: 'career-sense-of-purpose',
    title: 'Sense of purpose',
    description: 'Reflect on activities that give you energy.',
    impact: 71,
    category: 'ideal-gap',
  },
  {
    id: 'career-sense-of-purpose-s9',
    factorId: 'career-sense-of-purpose',
    title: 'Sense of purpose',
    description: 'List three meaningful things in life.',
    impact: 64,
    category: 'ideal-gap',
  },
  {
    id: 'career-sense-of-purpose-s10',
    factorId: 'career-sense-of-purpose',
    title: 'Sense of purpose',
    description: 'Work on something aligned with your values.',
    impact: 65,
    category: 'ideal-gap',
  },
  {
    id: 'career-skill-development-s1',
    factorId: 'career-skill-development',
    title: 'Skill development',
    description: 'Watch a tutorial on a useful skill.',
    impact: 65,
    category: 'ideal-gap',
  },
  {
    id: 'career-skill-development-s2',
    factorId: 'career-skill-development',
    title: 'Skill development',
    description: 'Read an article about a skill.',
    impact: 66,
    category: 'ideal-gap',
  },
  {
    id: 'career-skill-development-s3',
    factorId: 'career-skill-development',
    title: 'Skill development',
    description: 'Practice a skill for 20 minutes.',
    impact: 64,
    category: 'ideal-gap',
  },
  {
    id: 'career-skill-development-s4',
    factorId: 'career-skill-development',
    title: 'Skill development',
    description: 'Ask an expert for advice.',
    impact: 69,
    category: 'ideal-gap',
  },
  {
    id: 'career-skill-development-s5',
    factorId: 'career-skill-development',
    title: 'Skill development',
    description: 'Create a one‑month learning plan.',
    impact: 83,
    category: 'ideal-gap',
  },
  {
    id: 'career-skill-development-s6',
    factorId: 'career-skill-development',
    title: 'Skill development',
    description: 'Write notes about something new.',
    impact: 69,
    category: 'ideal-gap',
  },
  {
    id: 'career-skill-development-s7',
    factorId: 'career-skill-development',
    title: 'Skill development',
    description: 'Apply a new technique.',
    impact: 65,
    category: 'ideal-gap',
  },
  {
    id: 'career-skill-development-s8',
    factorId: 'career-skill-development',
    title: 'Skill development',
    description: 'Sign up for a short course.',
    impact: 77,
    category: 'ideal-gap',
  },
  {
    id: 'career-skill-development-s9',
    factorId: 'career-skill-development',
    title: 'Skill development',
    description: 'Teach someone a skill you know.',
    impact: 64,
    category: 'ideal-gap',
  },
  {
    id: 'career-skill-development-s10',
    factorId: 'career-skill-development',
    title: 'Skill development',
    description: 'Reflect on which skill would help your career.',
    impact: 70,
    category: 'ideal-gap',
  },
  {
    id: 'creativity-art-music-engagement-s1',
    factorId: 'creativity-art-music-engagement',
    title: 'Art/music engagement',
    description: 'Listen to music intentionally.',
    impact: 67,
    category: 'ideal-gap',
  },
  {
    id: 'creativity-art-music-engagement-s2',
    factorId: 'creativity-art-music-engagement',
    title: 'Art/music engagement',
    description: 'Visit an art gallery.',
    impact: 64,
    category: 'ideal-gap',
  },
  {
    id: 'creativity-art-music-engagement-s3',
    factorId: 'creativity-art-music-engagement',
    title: 'Art/music engagement',
    description: 'Explore a new music genre.',
    impact: 62,
    category: 'ideal-gap',
  },
  {
    id: 'creativity-art-music-engagement-s4',
    factorId: 'creativity-art-music-engagement',
    title: 'Art/music engagement',
    description: 'Attend a live performance.',
    impact: 63,
    category: 'ideal-gap',
  },
  {
    id: 'creativity-art-music-engagement-s5',
    factorId: 'creativity-art-music-engagement',
    title: 'Art/music engagement',
    description: 'Watch a creative performance online.',
    impact: 64,
    category: 'ideal-gap',
  },
  {
    id: 'creativity-art-music-engagement-s6',
    factorId: 'creativity-art-music-engagement',
    title: 'Art/music engagement',
    description: 'Create a playlist.',
    impact: 62,
    category: 'ideal-gap',
  },
  {
    id: 'creativity-art-music-engagement-s7',
    factorId: 'creativity-art-music-engagement',
    title: 'Art/music engagement',
    description: 'Reflect on a piece of art.',
    impact: 68,
    category: 'ideal-gap',
  },
  {
    id: 'creativity-art-music-engagement-s8',
    factorId: 'creativity-art-music-engagement',
    title: 'Art/music engagement',
    description: 'Read about an artist.',
    impact: 64,
    category: 'ideal-gap',
  },
  {
    id: 'creativity-art-music-engagement-s9',
    factorId: 'creativity-art-music-engagement',
    title: 'Art/music engagement',
    description: 'Explore creative works online.',
    impact: 62,
    category: 'ideal-gap',
  },
  {
    id: 'creativity-art-music-engagement-s10',
    factorId: 'creativity-art-music-engagement',
    title: 'Art/music engagement',
    description: 'Discuss art with someone.',
    impact: 63,
    category: 'ideal-gap',
  },
  {
    id: 'creativity-creating-writing-making-s1',
    factorId: 'creativity-creating-writing-making',
    title: 'Creating (writing/making/etc.)',
    description: 'Write a short journal entry.',
    impact: 67,
    category: 'ideal-gap',
  },
  {
    id: 'creativity-creating-writing-making-s2',
    factorId: 'creativity-creating-writing-making',
    title: 'Creating (writing/making/etc.)',
    description: 'Sketch something.',
    impact: 65,
    category: 'ideal-gap',
  },
  {
    id: 'creativity-creating-writing-making-s3',
    factorId: 'creativity-creating-writing-making',
    title: 'Creating (writing/making/etc.)',
    description: 'Write a short story.',
    impact: 66,
    category: 'ideal-gap',
  },
  {
    id: 'creativity-creating-writing-making-s4',
    factorId: 'creativity-creating-writing-making',
    title: 'Creating (writing/making/etc.)',
    description: 'Craft or build something simple.',
    impact: 64,
    category: 'ideal-gap',
  },
  {
    id: 'creativity-creating-writing-making-s5',
    factorId: 'creativity-creating-writing-making',
    title: 'Creating (writing/making/etc.)',
    description: 'Start a creative project.',
    impact: 65,
    category: 'ideal-gap',
  },
  {
    id: 'creativity-creating-writing-making-s6',
    factorId: 'creativity-creating-writing-making',
    title: 'Creating (writing/making/etc.)',
    description: 'Spend 20 minutes creating.',
    impact: 63,
    category: 'ideal-gap',
  },
  {
    id: 'creativity-creating-writing-making-s7',
    factorId: 'creativity-creating-writing-making',
    title: 'Creating (writing/making/etc.)',
    description: 'Experiment with a creative medium.',
    impact: 64,
    category: 'ideal-gap',
  },
  {
    id: 'creativity-creating-writing-making-s8',
    factorId: 'creativity-creating-writing-making',
    title: 'Creating (writing/making/etc.)',
    description: 'Create something imperfect for fun.',
    impact: 65,
    category: 'ideal-gap',
  },
  {
    id: 'creativity-creating-writing-making-s9',
    factorId: 'creativity-creating-writing-making',
    title: 'Creating (writing/making/etc.)',
    description: 'Document ideas in a notebook.',
    impact: 63,
    category: 'ideal-gap',
  },
  {
    id: 'creativity-creating-writing-making-s10',
    factorId: 'creativity-creating-writing-making',
    title: 'Creating (writing/making/etc.)',
    description: 'Share something you created.',
    impact: 68,
    category: 'ideal-gap',
  },
  {
    id: 'creativity-personal-style-self-expression-s1',
    factorId: 'creativity-personal-style-self-expression',
    title: 'Personal style / self-expression',
    description: 'Wear something that feels authentic.',
    impact: 63,
    category: 'ideal-gap',
  },
  {
    id: 'creativity-personal-style-self-expression-s2',
    factorId: 'creativity-personal-style-self-expression',
    title: 'Personal style / self-expression',
    description: 'Try a new outfit combination.',
    impact: 64,
    category: 'ideal-gap',
  },
  {
    id: 'creativity-personal-style-self-expression-s3',
    factorId: 'creativity-personal-style-self-expression',
    title: 'Personal style / self-expression',
    description: 'Refresh part of your wardrobe.',
    impact: 62,
    category: 'ideal-gap',
  },
  {
    id: 'creativity-personal-style-self-expression-s4',
    factorId: 'creativity-personal-style-self-expression',
    title: 'Personal style / self-expression',
    description: 'Express personality through style.',
    impact: 63,
    category: 'ideal-gap',
  },
  {
    id: 'creativity-personal-style-self-expression-s5',
    factorId: 'creativity-personal-style-self-expression',
    title: 'Personal style / self-expression',
    description: 'Reflect on your style preferences.',
    impact: 69,
    category: 'ideal-gap',
  },
  {
    id: 'creativity-personal-style-self-expression-s6',
    factorId: 'creativity-personal-style-self-expression',
    title: 'Personal style / self-expression',
    description: 'Experiment with a new look.',
    impact: 62,
    category: 'ideal-gap',
  },
  {
    id: 'creativity-personal-style-self-expression-s7',
    factorId: 'creativity-personal-style-self-expression',
    title: 'Personal style / self-expression',
    description: 'Choose something bold to wear.',
    impact: 63,
    category: 'ideal-gap',
  },
  {
    id: 'creativity-personal-style-self-expression-s8',
    factorId: 'creativity-personal-style-self-expression',
    title: 'Personal style / self-expression',
    description: 'Organize clothing you enjoy.',
    impact: 64,
    category: 'ideal-gap',
  },
  {
    id: 'creativity-personal-style-self-expression-s9',
    factorId: 'creativity-personal-style-self-expression',
    title: 'Personal style / self-expression',
    description: 'Take time getting ready intentionally.',
    impact: 62,
    category: 'ideal-gap',
  },
  {
    id: 'creativity-personal-style-self-expression-s10',
    factorId: 'creativity-personal-style-self-expression',
    title: 'Personal style / self-expression',
    description: 'Explore style inspiration.',
    impact: 63,
    category: 'ideal-gap',
  },
  {
    id: 'creativity-sharing-ideas-s1',
    factorId: 'creativity-sharing-ideas',
    title: 'Sharing ideas',
    description: 'Share a thought with a friend.',
    impact: 68,
    category: 'ideal-gap',
  },
  {
    id: 'creativity-sharing-ideas-s2',
    factorId: 'creativity-sharing-ideas',
    title: 'Sharing ideas',
    description: 'Write a short post about an idea.',
    impact: 68,
    category: 'ideal-gap',
  },
  {
    id: 'creativity-sharing-ideas-s3',
    factorId: 'creativity-sharing-ideas',
    title: 'Sharing ideas',
    description: 'Discuss something you\'re excited about.',
    impact: 63,
    category: 'ideal-gap',
  },
  {
    id: 'creativity-sharing-ideas-s4',
    factorId: 'creativity-sharing-ideas',
    title: 'Sharing ideas',
    description: 'Give thoughtful feedback.',
    impact: 64,
    category: 'ideal-gap',
  },
  {
    id: 'creativity-sharing-ideas-s5',
    factorId: 'creativity-sharing-ideas',
    title: 'Sharing ideas',
    description: 'Start a conversation about a topic.',
    impact: 65,
    category: 'ideal-gap',
  },
  {
    id: 'creativity-sharing-ideas-s6',
    factorId: 'creativity-sharing-ideas',
    title: 'Sharing ideas',
    description: 'Write down an idea clearly.',
    impact: 63,
    category: 'ideal-gap',
  },
  {
    id: 'creativity-sharing-ideas-s7',
    factorId: 'creativity-sharing-ideas',
    title: 'Sharing ideas',
    description: 'Present an idea in a meeting.',
    impact: 64,
    category: 'ideal-gap',
  },
  {
    id: 'creativity-sharing-ideas-s8',
    factorId: 'creativity-sharing-ideas',
    title: 'Sharing ideas',
    description: 'Share a useful resource.',
    impact: 69,
    category: 'ideal-gap',
  },
  {
    id: 'creativity-sharing-ideas-s9',
    factorId: 'creativity-sharing-ideas',
    title: 'Sharing ideas',
    description: 'Explain a concept you enjoy.',
    impact: 63,
    category: 'ideal-gap',
  },
  {
    id: 'creativity-sharing-ideas-s10',
    factorId: 'creativity-sharing-ideas',
    title: 'Sharing ideas',
    description: 'Contribute to a group discussion.',
    impact: 64,
    category: 'ideal-gap',
  },
  {
    id: 'environment-connection-to-nature-s1',
    factorId: 'environment-connection-to-nature',
    title: 'Connection to nature',
    description: 'Take a walk in a park.',
    impact: 72,
    category: 'ideal-gap',
  },
  {
    id: 'environment-connection-to-nature-s2',
    factorId: 'environment-connection-to-nature',
    title: 'Connection to nature',
    description: 'Spend 10 minutes outside.',
    impact: 68,
    category: 'ideal-gap',
  },
  {
    id: 'environment-connection-to-nature-s3',
    factorId: 'environment-connection-to-nature',
    title: 'Connection to nature',
    description: 'Visit a nature spot nearby.',
    impact: 63,
    category: 'ideal-gap',
  },
  {
    id: 'environment-connection-to-nature-s4',
    factorId: 'environment-connection-to-nature',
    title: 'Connection to nature',
    description: 'Sit outside quietly.',
    impact: 64,
    category: 'ideal-gap',
  },
  {
    id: 'environment-connection-to-nature-s5',
    factorId: 'environment-connection-to-nature',
    title: 'Connection to nature',
    description: 'Watch sunset or sunrise.',
    impact: 65,
    category: 'ideal-gap',
  },
  {
    id: 'environment-connection-to-nature-s6',
    factorId: 'environment-connection-to-nature',
    title: 'Connection to nature',
    description: 'Add plants to your space.',
    impact: 72,
    category: 'ideal-gap',
  },
  {
    id: 'environment-connection-to-nature-s7',
    factorId: 'environment-connection-to-nature',
    title: 'Connection to nature',
    description: 'Listen to nature sounds.',
    impact: 68,
    category: 'ideal-gap',
  },
  {
    id: 'environment-connection-to-nature-s8',
    factorId: 'environment-connection-to-nature',
    title: 'Connection to nature',
    description: 'Go on a short hike.',
    impact: 68,
    category: 'ideal-gap',
  },
  {
    id: 'environment-connection-to-nature-s9',
    factorId: 'environment-connection-to-nature',
    title: 'Connection to nature',
    description: 'Eat a meal outside.',
    impact: 63,
    category: 'ideal-gap',
  },
  {
    id: 'environment-connection-to-nature-s10',
    factorId: 'environment-connection-to-nature',
    title: 'Connection to nature',
    description: 'Observe nature mindfully.',
    impact: 64,
    category: 'ideal-gap',
  },
  {
    id: 'environment-home-comfort-s1',
    factorId: 'environment-home-comfort',
    title: 'Home comfort',
    description: 'Declutter one area of your home.',
    impact: 64,
    category: 'ideal-gap',
  },
  {
    id: 'environment-home-comfort-s2',
    factorId: 'environment-home-comfort',
    title: 'Home comfort',
    description: 'Add something cozy to your space.',
    impact: 65,
    category: 'ideal-gap',
  },
  {
    id: 'environment-home-comfort-s3',
    factorId: 'environment-home-comfort',
    title: 'Home comfort',
    description: 'Clean or organize a room.',
    impact: 63,
    category: 'ideal-gap',
  },
  {
    id: 'environment-home-comfort-s4',
    factorId: 'environment-home-comfort',
    title: 'Home comfort',
    description: 'Improve lighting in a room.',
    impact: 72,
    category: 'ideal-gap',
  },
  {
    id: 'environment-home-comfort-s5',
    factorId: 'environment-home-comfort',
    title: 'Home comfort',
    description: 'Create a relaxing corner.',
    impact: 65,
    category: 'ideal-gap',
  },
  {
    id: 'environment-home-comfort-s6',
    factorId: 'environment-home-comfort',
    title: 'Home comfort',
    description: 'Do a quick tidy session.',
    impact: 66,
    category: 'ideal-gap',
  },
  {
    id: 'environment-home-comfort-s7',
    factorId: 'environment-home-comfort',
    title: 'Home comfort',
    description: 'Open windows for fresh air.',
    impact: 64,
    category: 'ideal-gap',
  },
  {
    id: 'environment-home-comfort-s8',
    factorId: 'environment-home-comfort',
    title: 'Home comfort',
    description: 'Add a plant.',
    impact: 74,
    category: 'ideal-gap',
  },
  {
    id: 'environment-home-comfort-s9',
    factorId: 'environment-home-comfort',
    title: 'Home comfort',
    description: 'Improve seating comfort.',
    impact: 71,
    category: 'ideal-gap',
  },
  {
    id: 'environment-home-comfort-s10',
    factorId: 'environment-home-comfort',
    title: 'Home comfort',
    description: 'Make your bedroom more inviting.',
    impact: 64,
    category: 'ideal-gap',
  },
  {
    id: 'environment-organization-clutter-s1',
    factorId: 'environment-organization-clutter',
    title: 'Organization / clutter',
    description: 'Declutter a drawer.',
    impact: 64,
    category: 'ideal-gap',
  },
  {
    id: 'environment-organization-clutter-s2',
    factorId: 'environment-organization-clutter',
    title: 'Organization / clutter',
    description: 'Sort old documents.',
    impact: 65,
    category: 'ideal-gap',
  },
  {
    id: 'environment-organization-clutter-s3',
    factorId: 'environment-organization-clutter',
    title: 'Organization / clutter',
    description: 'Organize digital files.',
    impact: 63,
    category: 'ideal-gap',
  },
  {
    id: 'environment-organization-clutter-s4',
    factorId: 'environment-organization-clutter',
    title: 'Organization / clutter',
    description: 'Create a simple system.',
    impact: 64,
    category: 'ideal-gap',
  },
  {
    id: 'environment-organization-clutter-s5',
    factorId: 'environment-organization-clutter',
    title: 'Organization / clutter',
    description: 'Throw away unused items.',
    impact: 65,
    category: 'ideal-gap',
  },
  {
    id: 'environment-organization-clutter-s6',
    factorId: 'environment-organization-clutter',
    title: 'Organization / clutter',
    description: 'Clean your desktop.',
    impact: 63,
    category: 'ideal-gap',
  },
  {
    id: 'environment-organization-clutter-s7',
    factorId: 'environment-organization-clutter',
    title: 'Organization / clutter',
    description: 'Donate unused things.',
    impact: 64,
    category: 'ideal-gap',
  },
  {
    id: 'environment-organization-clutter-s8',
    factorId: 'environment-organization-clutter',
    title: 'Organization / clutter',
    description: 'Label storage areas.',
    impact: 65,
    category: 'ideal-gap',
  },
  {
    id: 'environment-organization-clutter-s9',
    factorId: 'environment-organization-clutter',
    title: 'Organization / clutter',
    description: 'Spend 10 minutes tidying.',
    impact: 66,
    category: 'ideal-gap',
  },
  {
    id: 'environment-organization-clutter-s10',
    factorId: 'environment-organization-clutter',
    title: 'Organization / clutter',
    description: 'Reduce clutter in one room.',
    impact: 64,
    category: 'ideal-gap',
  },
  {
    id: 'environment-workspace-quality-s1',
    factorId: 'environment-workspace-quality',
    title: 'Workspace quality',
    description: 'Organize your desk.',
    impact: 64,
    category: 'ideal-gap',
  },
  {
    id: 'environment-workspace-quality-s2',
    factorId: 'environment-workspace-quality',
    title: 'Workspace quality',
    description: 'Remove clutter from workspace.',
    impact: 65,
    category: 'ideal-gap',
  },
  {
    id: 'environment-workspace-quality-s3',
    factorId: 'environment-workspace-quality',
    title: 'Workspace quality',
    description: 'Improve chair posture setup.',
    impact: 71,
    category: 'ideal-gap',
  },
  {
    id: 'environment-workspace-quality-s4',
    factorId: 'environment-workspace-quality',
    title: 'Workspace quality',
    description: 'Adjust lighting.',
    impact: 64,
    category: 'ideal-gap',
  },
  {
    id: 'environment-workspace-quality-s5',
    factorId: 'environment-workspace-quality',
    title: 'Workspace quality',
    description: 'Clean the desk surface.',
    impact: 65,
    category: 'ideal-gap',
  },
  {
    id: 'environment-workspace-quality-s6',
    factorId: 'environment-workspace-quality',
    title: 'Workspace quality',
    description: 'Add something inspiring to your desk.',
    impact: 63,
    category: 'ideal-gap',
  },
  {
    id: 'environment-workspace-quality-s7',
    factorId: 'environment-workspace-quality',
    title: 'Workspace quality',
    description: 'Adjust monitor height.',
    impact: 64,
    category: 'ideal-gap',
  },
  {
    id: 'environment-workspace-quality-s8',
    factorId: 'environment-workspace-quality',
    title: 'Workspace quality',
    description: 'Reduce distractions.',
    impact: 65,
    category: 'ideal-gap',
  },
  {
    id: 'environment-workspace-quality-s9',
    factorId: 'environment-workspace-quality',
    title: 'Workspace quality',
    description: 'Create a focused work zone.',
    impact: 63,
    category: 'ideal-gap',
  },
  {
    id: 'environment-workspace-quality-s10',
    factorId: 'environment-workspace-quality',
    title: 'Workspace quality',
    description: 'Refresh workspace layout.',
    impact: 64,
    category: 'ideal-gap',
  },
  {
    id: 'finances-financial-goals-clarity-s1',
    factorId: 'finances-financial-goals-clarity',
    title: 'Financial goals / clarity',
    description: 'Write down top financial goals.',
    impact: 76,
    category: 'ideal-gap',
  },
  {
    id: 'finances-financial-goals-clarity-s2',
    factorId: 'finances-financial-goals-clarity',
    title: 'Financial goals / clarity',
    description: 'Estimate cost of one goal.',
    impact: 77,
    category: 'ideal-gap',
  },
  {
    id: 'finances-financial-goals-clarity-s3',
    factorId: 'finances-financial-goals-clarity',
    title: 'Financial goals / clarity',
    description: 'Create a simple monthly budget.',
    impact: 85,
    category: 'ideal-gap',
  },
  {
    id: 'finances-financial-goals-clarity-s4',
    factorId: 'finances-financial-goals-clarity',
    title: 'Financial goals / clarity',
    description: 'Break a big goal into steps.',
    impact: 76,
    category: 'ideal-gap',
  },
  {
    id: 'finances-financial-goals-clarity-s5',
    factorId: 'finances-financial-goals-clarity',
    title: 'Financial goals / clarity',
    description: 'Review financial progress.',
    impact: 73,
    category: 'ideal-gap',
  },
  {
    id: 'finances-financial-goals-clarity-s6',
    factorId: 'finances-financial-goals-clarity',
    title: 'Financial goals / clarity',
    description: 'Set a timeline for a goal.',
    impact: 75,
    category: 'ideal-gap',
  },
  {
    id: 'finances-financial-goals-clarity-s7',
    factorId: 'finances-financial-goals-clarity',
    title: 'Financial goals / clarity',
    description: 'Schedule monthly finance review.',
    impact: 82,
    category: 'ideal-gap',
  },
  {
    id: 'finances-financial-goals-clarity-s8',
    factorId: 'finances-financial-goals-clarity',
    title: 'Financial goals / clarity',
    description: 'Define what financial freedom means to you.',
    impact: 68,
    category: 'ideal-gap',
  },
  {
    id: 'finances-financial-goals-clarity-s9',
    factorId: 'finances-financial-goals-clarity',
    title: 'Financial goals / clarity',
    description: 'List actions to improve finances.',
    impact: 74,
    category: 'ideal-gap',
  },
  {
    id: 'finances-financial-goals-clarity-s10',
    factorId: 'finances-financial-goals-clarity',
    title: 'Financial goals / clarity',
    description: 'Discuss money goals with someone.',
    impact: 76,
    category: 'ideal-gap',
  },
  {
    id: 'finances-income-stability-s1',
    factorId: 'finances-income-stability',
    title: 'Income stability',
    description: 'Review your income sources.',
    impact: 73,
    category: 'ideal-gap',
  },
  {
    id: 'finances-income-stability-s2',
    factorId: 'finances-income-stability',
    title: 'Income stability',
    description: 'Update your resume.',
    impact: 69,
    category: 'ideal-gap',
  },
  {
    id: 'finances-income-stability-s3',
    factorId: 'finances-income-stability',
    title: 'Income stability',
    description: 'Research ways to increase income.',
    impact: 67,
    category: 'ideal-gap',
  },
  {
    id: 'finances-income-stability-s4',
    factorId: 'finances-income-stability',
    title: 'Income stability',
    description: 'Track income this week.',
    impact: 73,
    category: 'ideal-gap',
  },
  {
    id: 'finances-income-stability-s5',
    factorId: 'finances-income-stability',
    title: 'Income stability',
    description: 'Identify a skill that boosts earnings.',
    impact: 69,
    category: 'ideal-gap',
  },
  {
    id: 'finances-income-stability-s6',
    factorId: 'finances-income-stability',
    title: 'Income stability',
    description: 'Reach out to a professional contact.',
    impact: 67,
    category: 'ideal-gap',
  },
  {
    id: 'finances-income-stability-s7',
    factorId: 'finances-income-stability',
    title: 'Income stability',
    description: 'Explore freelance opportunities.',
    impact: 68,
    category: 'ideal-gap',
  },
  {
    id: 'finances-income-stability-s8',
    factorId: 'finances-income-stability',
    title: 'Income stability',
    description: 'Reflect on improving financial stability.',
    impact: 74,
    category: 'ideal-gap',
  },
  {
    id: 'finances-income-stability-s9',
    factorId: 'finances-income-stability',
    title: 'Income stability',
    description: 'Set a yearly financial improvement goal.',
    impact: 86,
    category: 'ideal-gap',
  },
  {
    id: 'finances-income-stability-s10',
    factorId: 'finances-income-stability',
    title: 'Income stability',
    description: 'Look into career growth options.',
    impact: 68,
    category: 'ideal-gap',
  },
  {
    id: 'finances-savings-investments-s1',
    factorId: 'finances-savings-investments',
    title: 'Savings & investments',
    description: 'Check your savings balance.',
    impact: 68,
    category: 'ideal-gap',
  },
  {
    id: 'finances-savings-investments-s2',
    factorId: 'finances-savings-investments',
    title: 'Savings & investments',
    description: 'Set up automatic savings.',
    impact: 79,
    category: 'ideal-gap',
  },
  {
    id: 'finances-savings-investments-s3',
    factorId: 'finances-savings-investments',
    title: 'Savings & investments',
    description: 'Research basic investing.',
    impact: 67,
    category: 'ideal-gap',
  },
  {
    id: 'finances-savings-investments-s4',
    factorId: 'finances-savings-investments',
    title: 'Savings & investments',
    description: 'Increase your savings slightly.',
    impact: 68,
    category: 'ideal-gap',
  },
  {
    id: 'finances-savings-investments-s5',
    factorId: 'finances-savings-investments',
    title: 'Savings & investments',
    description: 'Review long‑term goals.',
    impact: 83,
    category: 'ideal-gap',
  },
  {
    id: 'finances-savings-investments-s6',
    factorId: 'finances-savings-investments',
    title: 'Savings & investments',
    description: 'Transfer a small amount to savings.',
    impact: 67,
    category: 'ideal-gap',
  },
  {
    id: 'finances-savings-investments-s7',
    factorId: 'finances-savings-investments',
    title: 'Savings & investments',
    description: 'Read about investing basics.',
    impact: 68,
    category: 'ideal-gap',
  },
  {
    id: 'finances-savings-investments-s8',
    factorId: 'finances-savings-investments',
    title: 'Savings & investments',
    description: 'Track monthly savings progress.',
    impact: 84,
    category: 'ideal-gap',
  },
  {
    id: 'finances-savings-investments-s9',
    factorId: 'finances-savings-investments',
    title: 'Savings & investments',
    description: 'Set a savings milestone.',
    impact: 76,
    category: 'ideal-gap',
  },
  {
    id: 'finances-savings-investments-s10',
    factorId: 'finances-savings-investments',
    title: 'Savings & investments',
    description: 'Review emergency fund status.',
    impact: 73,
    category: 'ideal-gap',
  },
  {
    id: 'finances-spending-habits-s1',
    factorId: 'finances-spending-habits',
    title: 'Spending habits',
    description: 'Review recent transactions.',
    impact: 72,
    category: 'ideal-gap',
  },
  {
    id: 'finances-spending-habits-s2',
    factorId: 'finances-spending-habits',
    title: 'Spending habits',
    description: 'Cancel an unused subscription.',
    impact: 76,
    category: 'ideal-gap',
  },
  {
    id: 'finances-spending-habits-s3',
    factorId: 'finances-spending-habits',
    title: 'Spending habits',
    description: 'Track spending today.',
    impact: 69,
    category: 'ideal-gap',
  },
  {
    id: 'finances-spending-habits-s4',
    factorId: 'finances-spending-habits',
    title: 'Spending habits',
    description: 'Pause before making purchases.',
    impact: 67,
    category: 'ideal-gap',
  },
  {
    id: 'finances-spending-habits-s5',
    factorId: 'finances-spending-habits',
    title: 'Spending habits',
    description: 'Set a weekly spending limit.',
    impact: 78,
    category: 'ideal-gap',
  },
  {
    id: 'finances-spending-habits-s6',
    factorId: 'finances-spending-habits',
    title: 'Spending habits',
    description: 'Reflect on purchases that brought value.',
    impact: 71,
    category: 'ideal-gap',
  },
  {
    id: 'finances-spending-habits-s7',
    factorId: 'finances-spending-habits',
    title: 'Spending habits',
    description: 'Identify one unnecessary expense.',
    impact: 67,
    category: 'ideal-gap',
  },
  {
    id: 'finances-spending-habits-s8',
    factorId: 'finances-spending-habits',
    title: 'Spending habits',
    description: 'Delay a purchase for 24 hours.',
    impact: 68,
    category: 'ideal-gap',
  },
  {
    id: 'finances-spending-habits-s9',
    factorId: 'finances-spending-habits',
    title: 'Spending habits',
    description: 'Plan a weekly budget.',
    impact: 85,
    category: 'ideal-gap',
  },
  {
    id: 'finances-spending-habits-s10',
    factorId: 'finances-spending-habits',
    title: 'Spending habits',
    description: 'Notice impulse purchases.',
    impact: 67,
    category: 'ideal-gap',
  },
  {
    id: 'growth-learning-education-s1',
    factorId: 'growth-learning-education',
    title: 'Learning & education',
    description: 'Read 10 pages of a book.',
    impact: 64,
    category: 'ideal-gap',
  },
  {
    id: 'growth-learning-education-s2',
    factorId: 'growth-learning-education',
    title: 'Learning & education',
    description: 'Watch an educational video.',
    impact: 65,
    category: 'ideal-gap',
  },
  {
    id: 'growth-learning-education-s3',
    factorId: 'growth-learning-education',
    title: 'Learning & education',
    description: 'Take notes on something new.',
    impact: 68,
    category: 'ideal-gap',
  },
  {
    id: 'growth-learning-education-s4',
    factorId: 'growth-learning-education',
    title: 'Learning & education',
    description: 'Study a topic for 20 minutes.',
    impact: 64,
    category: 'ideal-gap',
  },
  {
    id: 'growth-learning-education-s5',
    factorId: 'growth-learning-education',
    title: 'Learning & education',
    description: 'Explore a new subject online.',
    impact: 65,
    category: 'ideal-gap',
  },
  {
    id: 'growth-learning-education-s6',
    factorId: 'growth-learning-education',
    title: 'Learning & education',
    description: 'Write questions you\'re curious about.',
    impact: 63,
    category: 'ideal-gap',
  },
  {
    id: 'growth-learning-education-s7',
    factorId: 'growth-learning-education',
    title: 'Learning & education',
    description: 'Listen to an educational podcast.',
    impact: 68,
    category: 'ideal-gap',
  },
  {
    id: 'growth-learning-education-s8',
    factorId: 'growth-learning-education',
    title: 'Learning & education',
    description: 'Join an online learning platform.',
    impact: 65,
    category: 'ideal-gap',
  },
  {
    id: 'growth-learning-education-s9',
    factorId: 'growth-learning-education',
    title: 'Learning & education',
    description: 'Review something you learned recently.',
    impact: 68,
    category: 'ideal-gap',
  },
  {
    id: 'growth-learning-education-s10',
    factorId: 'growth-learning-education',
    title: 'Learning & education',
    description: 'Teach someone what you learned.',
    impact: 64,
    category: 'ideal-gap',
  },
  {
    id: 'growth-resilience-stress-coping-s1',
    factorId: 'growth-resilience-stress-coping',
    title: 'Resilience / stress coping',
    description: 'Take a short break when stressed.',
    impact: 68,
    category: 'ideal-gap',
  },
  {
    id: 'growth-resilience-stress-coping-s2',
    factorId: 'growth-resilience-stress-coping',
    title: 'Resilience / stress coping',
    description: 'Write down what\'s causing stress.',
    impact: 66,
    category: 'ideal-gap',
  },
  {
    id: 'growth-resilience-stress-coping-s3',
    factorId: 'growth-resilience-stress-coping',
    title: 'Resilience / stress coping',
    description: 'Break a problem into steps.',
    impact: 64,
    category: 'ideal-gap',
  },
  {
    id: 'growth-resilience-stress-coping-s4',
    factorId: 'growth-resilience-stress-coping',
    title: 'Resilience / stress coping',
    description: 'Talk to someone about a challenge.',
    impact: 69,
    category: 'ideal-gap',
  },
  {
    id: 'growth-resilience-stress-coping-s5',
    factorId: 'growth-resilience-stress-coping',
    title: 'Resilience / stress coping',
    description: 'Practice deep breathing.',
    impact: 74,
    category: 'ideal-gap',
  },
  {
    id: 'growth-resilience-stress-coping-s6',
    factorId: 'growth-resilience-stress-coping',
    title: 'Resilience / stress coping',
    description: 'Go for a clearing walk.',
    impact: 72,
    category: 'ideal-gap',
  },
  {
    id: 'growth-resilience-stress-coping-s7',
    factorId: 'growth-resilience-stress-coping',
    title: 'Resilience / stress coping',
    description: 'Write possible solutions.',
    impact: 65,
    category: 'ideal-gap',
  },
  {
    id: 'growth-resilience-stress-coping-s8',
    factorId: 'growth-resilience-stress-coping',
    title: 'Resilience / stress coping',
    description: 'Remember past challenges you overcame.',
    impact: 66,
    category: 'ideal-gap',
  },
  {
    id: 'growth-resilience-stress-coping-s9',
    factorId: 'growth-resilience-stress-coping',
    title: 'Resilience / stress coping',
    description: 'Focus on what you control.',
    impact: 64,
    category: 'ideal-gap',
  },
  {
    id: 'growth-resilience-stress-coping-s10',
    factorId: 'growth-resilience-stress-coping',
    title: 'Resilience / stress coping',
    description: 'Take one small step toward a solution.',
    impact: 65,
    category: 'ideal-gap',
  },
  {
    id: 'growth-self-reflection-s1',
    factorId: 'growth-self-reflection',
    title: 'Self-reflection',
    description: 'Journal about your day.',
    impact: 64,
    category: 'ideal-gap',
  },
  {
    id: 'growth-self-reflection-s2',
    factorId: 'growth-self-reflection',
    title: 'Self-reflection',
    description: 'Reflect on what went well.',
    impact: 70,
    category: 'ideal-gap',
  },
  {
    id: 'growth-self-reflection-s3',
    factorId: 'growth-self-reflection',
    title: 'Self-reflection',
    description: 'Write about something to improve.',
    impact: 71,
    category: 'ideal-gap',
  },
  {
    id: 'growth-self-reflection-s4',
    factorId: 'growth-self-reflection',
    title: 'Self-reflection',
    description: 'Review your goals.',
    impact: 78,
    category: 'ideal-gap',
  },
  {
    id: 'growth-self-reflection-s5',
    factorId: 'growth-self-reflection',
    title: 'Self-reflection',
    description: 'Think about a recent decision.',
    impact: 65,
    category: 'ideal-gap',
  },
  {
    id: 'growth-self-reflection-s6',
    factorId: 'growth-self-reflection',
    title: 'Self-reflection',
    description: 'Ask yourself what you\'re avoiding.',
    impact: 67,
    category: 'ideal-gap',
  },
  {
    id: 'growth-self-reflection-s7',
    factorId: 'growth-self-reflection',
    title: 'Self-reflection',
    description: 'Reflect on what energizes you.',
    impact: 69,
    category: 'ideal-gap',
  },
  {
    id: 'growth-self-reflection-s8',
    factorId: 'growth-self-reflection',
    title: 'Self-reflection',
    description: 'Write what matters most to you.',
    impact: 65,
    category: 'ideal-gap',
  },
  {
    id: 'growth-self-reflection-s9',
    factorId: 'growth-self-reflection',
    title: 'Self-reflection',
    description: 'Reflect on a recent challenge.',
    impact: 68,
    category: 'ideal-gap',
  },
  {
    id: 'growth-self-reflection-s10',
    factorId: 'growth-self-reflection',
    title: 'Self-reflection',
    description: 'Write one lesson from today.',
    impact: 62,
    category: 'ideal-gap',
  },
  {
    id: 'growth-trying-new-things-s1',
    factorId: 'growth-trying-new-things',
    title: 'Trying new things',
    description: 'Try a new café or restaurant.',
    impact: 63,
    category: 'ideal-gap',
  },
  {
    id: 'growth-trying-new-things-s2',
    factorId: 'growth-trying-new-things',
    title: 'Trying new things',
    description: 'Cook a new recipe.',
    impact: 64,
    category: 'ideal-gap',
  },
  {
    id: 'growth-trying-new-things-s3',
    factorId: 'growth-trying-new-things',
    title: 'Trying new things',
    description: 'Start a new hobby.',
    impact: 62,
    category: 'ideal-gap',
  },
  {
    id: 'growth-trying-new-things-s4',
    factorId: 'growth-trying-new-things',
    title: 'Trying new things',
    description: 'Explore a new part of your city.',
    impact: 63,
    category: 'ideal-gap',
  },
  {
    id: 'growth-trying-new-things-s5',
    factorId: 'growth-trying-new-things',
    title: 'Trying new things',
    description: 'Attend a new event.',
    impact: 64,
    category: 'ideal-gap',
  },
  {
    id: 'growth-trying-new-things-s6',
    factorId: 'growth-trying-new-things',
    title: 'Trying new things',
    description: 'Talk to someone new.',
    impact: 66,
    category: 'ideal-gap',
  },
  {
    id: 'growth-trying-new-things-s7',
    factorId: 'growth-trying-new-things',
    title: 'Trying new things',
    description: 'Experiment with a creative activity.',
    impact: 63,
    category: 'ideal-gap',
  },
  {
    id: 'growth-trying-new-things-s8',
    factorId: 'growth-trying-new-things',
    title: 'Trying new things',
    description: 'Watch a documentary about a new topic.',
    impact: 64,
    category: 'ideal-gap',
  },
  {
    id: 'growth-trying-new-things-s9',
    factorId: 'growth-trying-new-things',
    title: 'Trying new things',
    description: 'Change your routine slightly.',
    impact: 62,
    category: 'ideal-gap',
  },
  {
    id: 'growth-trying-new-things-s10',
    factorId: 'growth-trying-new-things',
    title: 'Trying new things',
    description: 'Say yes to a small opportunity.',
    impact: 63,
    category: 'ideal-gap',
  },
  {
    id: 'health-mental-well-being-s1',
    factorId: 'health-mental-well-being',
    title: 'Mental well-being',
    description: 'Take 10 minutes to meditate.',
    impact: 78,
    category: 'ideal-gap',
  },
  {
    id: 'health-mental-well-being-s2',
    factorId: 'health-mental-well-being',
    title: 'Mental well-being',
    description: 'Write down three things you\'re grateful for.',
    impact: 68,
    category: 'ideal-gap',
  },
  {
    id: 'health-mental-well-being-s3',
    factorId: 'health-mental-well-being',
    title: 'Mental well-being',
    description: 'Step outside for fresh air.',
    impact: 69,
    category: 'ideal-gap',
  },
  {
    id: 'health-mental-well-being-s4',
    factorId: 'health-mental-well-being',
    title: 'Mental well-being',
    description: 'Practice slow breathing.',
    impact: 75,
    category: 'ideal-gap',
  },
  {
    id: 'health-mental-well-being-s5',
    factorId: 'health-mental-well-being',
    title: 'Mental well-being',
    description: 'Write down what\'s stressing you.',
    impact: 68,
    category: 'ideal-gap',
  },
  {
    id: 'health-mental-well-being-s6',
    factorId: 'health-mental-well-being',
    title: 'Mental well-being',
    description: 'Talk to someone you trust.',
    impact: 70,
    category: 'ideal-gap',
  },
  {
    id: 'health-mental-well-being-s7',
    factorId: 'health-mental-well-being',
    title: 'Mental well-being',
    description: 'Take a break from social media.',
    impact: 67,
    category: 'ideal-gap',
  },
  {
    id: 'health-mental-well-being-s8',
    factorId: 'health-mental-well-being',
    title: 'Mental well-being',
    description: 'Listen to calming music.',
    impact: 72,
    category: 'ideal-gap',
  },
  {
    id: 'health-mental-well-being-s9',
    factorId: 'health-mental-well-being',
    title: 'Mental well-being',
    description: 'Do something relaxing.',
    impact: 66,
    category: 'ideal-gap',
  },
  {
    id: 'health-mental-well-being-s10',
    factorId: 'health-mental-well-being',
    title: 'Mental well-being',
    description: 'Reflect on one good thing today.',
    impact: 70,
    category: 'ideal-gap',
  },
  {
    id: 'health-nutrition-s1',
    factorId: 'health-nutrition',
    title: 'Nutrition',
    description: 'Cook one healthy meal today.',
    impact: 65,
    category: 'ideal-gap',
  },
  {
    id: 'health-nutrition-s2',
    factorId: 'health-nutrition',
    title: 'Nutrition',
    description: 'Add vegetables to your next meal.',
    impact: 68,
    category: 'ideal-gap',
  },
  {
    id: 'health-nutrition-s3',
    factorId: 'health-nutrition',
    title: 'Nutrition',
    description: 'Drink a glass of water before meals.',
    impact: 66,
    category: 'ideal-gap',
  },
  {
    id: 'health-nutrition-s4',
    factorId: 'health-nutrition',
    title: 'Nutrition',
    description: 'Plan tomorrow\'s meals.',
    impact: 76,
    category: 'ideal-gap',
  },
  {
    id: 'health-nutrition-s5',
    factorId: 'health-nutrition',
    title: 'Nutrition',
    description: 'Replace a sugary snack with fruit.',
    impact: 68,
    category: 'ideal-gap',
  },
  {
    id: 'health-nutrition-s6',
    factorId: 'health-nutrition',
    title: 'Nutrition',
    description: 'Track what you eat today.',
    impact: 69,
    category: 'ideal-gap',
  },
  {
    id: 'health-nutrition-s7',
    factorId: 'health-nutrition',
    title: 'Nutrition',
    description: 'Prepare a healthy snack.',
    impact: 67,
    category: 'ideal-gap',
  },
  {
    id: 'health-nutrition-s8',
    factorId: 'health-nutrition',
    title: 'Nutrition',
    description: 'Eat one meal without distractions.',
    impact: 68,
    category: 'ideal-gap',
  },
  {
    id: 'health-nutrition-s9',
    factorId: 'health-nutrition',
    title: 'Nutrition',
    description: 'Try a new healthy recipe.',
    impact: 66,
    category: 'ideal-gap',
  },
  {
    id: 'health-nutrition-s10',
    factorId: 'health-nutrition',
    title: 'Nutrition',
    description: 'Reduce processed food today.',
    impact: 65,
    category: 'ideal-gap',
  },
  {
    id: 'health-physical-activity-s1',
    factorId: 'health-physical-activity',
    title: 'Physical activity',
    description: 'Take a 30‑minute walk.',
    impact: 75,
    category: 'ideal-gap',
  },
  {
    id: 'health-physical-activity-s2',
    factorId: 'health-physical-activity',
    title: 'Physical activity',
    description: 'Do a short home workout.',
    impact: 79,
    category: 'ideal-gap',
  },
  {
    id: 'health-physical-activity-s3',
    factorId: 'health-physical-activity',
    title: 'Physical activity',
    description: 'Go for a bike ride or jog.',
    impact: 66,
    category: 'ideal-gap',
  },
  {
    id: 'health-physical-activity-s4',
    factorId: 'health-physical-activity',
    title: 'Physical activity',
    description: 'Take the stairs today.',
    impact: 65,
    category: 'ideal-gap',
  },
  {
    id: 'health-physical-activity-s5',
    factorId: 'health-physical-activity',
    title: 'Physical activity',
    description: 'Try a new fitness class.',
    impact: 68,
    category: 'ideal-gap',
  },
  {
    id: 'health-physical-activity-s6',
    factorId: 'health-physical-activity',
    title: 'Physical activity',
    description: 'Schedule a workout session.',
    impact: 84,
    category: 'ideal-gap',
  },
  {
    id: 'health-physical-activity-s7',
    factorId: 'health-physical-activity',
    title: 'Physical activity',
    description: 'Do 10 minutes of stretching.',
    impact: 70,
    category: 'ideal-gap',
  },
  {
    id: 'health-physical-activity-s8',
    factorId: 'health-physical-activity',
    title: 'Physical activity',
    description: 'Walk during a phone call.',
    impact: 80,
    category: 'ideal-gap',
  },
  {
    id: 'health-physical-activity-s9',
    factorId: 'health-physical-activity',
    title: 'Physical activity',
    description: 'Set a step goal for today.',
    impact: 73,
    category: 'ideal-gap',
  },
  {
    id: 'health-physical-activity-s10',
    factorId: 'health-physical-activity',
    title: 'Physical activity',
    description: 'Do a quick bodyweight workout.',
    impact: 78,
    category: 'ideal-gap',
  },
  {
    id: 'health-sleep-quality-s1',
    factorId: 'health-sleep-quality',
    title: 'Sleep quality',
    description: 'Go to bed 30 minutes earlier.',
    impact: 68,
    category: 'ideal-gap',
  },
  {
    id: 'health-sleep-quality-s2',
    factorId: 'health-sleep-quality',
    title: 'Sleep quality',
    description: 'Stop using screens before bed.',
    impact: 69,
    category: 'ideal-gap',
  },
  {
    id: 'health-sleep-quality-s3',
    factorId: 'health-sleep-quality',
    title: 'Sleep quality',
    description: 'Create a relaxing bedtime routine.',
    impact: 67,
    category: 'ideal-gap',
  },
  {
    id: 'health-sleep-quality-s4',
    factorId: 'health-sleep-quality',
    title: 'Sleep quality',
    description: 'Keep a consistent bedtime tonight.',
    impact: 66,
    category: 'ideal-gap',
  },
  {
    id: 'health-sleep-quality-s5',
    factorId: 'health-sleep-quality',
    title: 'Sleep quality',
    description: 'Reduce caffeine in the afternoon.',
    impact: 69,
    category: 'ideal-gap',
  },
  {
    id: 'health-sleep-quality-s6',
    factorId: 'health-sleep-quality',
    title: 'Sleep quality',
    description: 'Make your bedroom darker or quieter.',
    impact: 67,
    category: 'ideal-gap',
  },
  {
    id: 'health-sleep-quality-s7',
    factorId: 'health-sleep-quality',
    title: 'Sleep quality',
    description: 'Write tomorrow\'s tasks before sleeping.',
    impact: 80,
    category: 'ideal-gap',
  },
  {
    id: 'health-sleep-quality-s8',
    factorId: 'health-sleep-quality',
    title: 'Sleep quality',
    description: 'Read a book before bed.',
    impact: 69,
    category: 'ideal-gap',
  },
  {
    id: 'health-sleep-quality-s9',
    factorId: 'health-sleep-quality',
    title: 'Sleep quality',
    description: 'Wake up at the same time tomorrow.',
    impact: 67,
    category: 'ideal-gap',
  },
  {
    id: 'health-sleep-quality-s10',
    factorId: 'health-sleep-quality',
    title: 'Sleep quality',
    description: 'Track your sleep tonight.',
    impact: 79,
    category: 'ideal-gap',
  },
  {
    id: 'leisure-entertainment-s1',
    factorId: 'leisure-entertainment',
    title: 'Entertainment',
    description: 'Watch a movie you’ve been meaning to see.',
    impact: 62,
    category: 'ideal-gap',
  },
  {
    id: 'leisure-entertainment-s2',
    factorId: 'leisure-entertainment',
    title: 'Entertainment',
    description: 'Listen to new music.',
    impact: 67,
    category: 'ideal-gap',
  },
  {
    id: 'leisure-entertainment-s3',
    factorId: 'leisure-entertainment',
    title: 'Entertainment',
    description: 'Read a novel.',
    impact: 61,
    category: 'ideal-gap',
  },
  {
    id: 'leisure-entertainment-s4',
    factorId: 'leisure-entertainment',
    title: 'Entertainment',
    description: 'Watch a documentary.',
    impact: 62,
    category: 'ideal-gap',
  },
  {
    id: 'leisure-entertainment-s5',
    factorId: 'leisure-entertainment',
    title: 'Entertainment',
    description: 'Play a casual game.',
    impact: 63,
    category: 'ideal-gap',
  },
  {
    id: 'leisure-entertainment-s6',
    factorId: 'leisure-entertainment',
    title: 'Entertainment',
    description: 'Visit a cinema or theatre.',
    impact: 61,
    category: 'ideal-gap',
  },
  {
    id: 'leisure-entertainment-s7',
    factorId: 'leisure-entertainment',
    title: 'Entertainment',
    description: 'Explore new podcasts.',
    impact: 62,
    category: 'ideal-gap',
  },
  {
    id: 'leisure-entertainment-s8',
    factorId: 'leisure-entertainment',
    title: 'Entertainment',
    description: 'Take a break with entertainment.',
    impact: 63,
    category: 'ideal-gap',
  },
  {
    id: 'leisure-entertainment-s9',
    factorId: 'leisure-entertainment',
    title: 'Entertainment',
    description: 'Rewatch something you love.',
    impact: 61,
    category: 'ideal-gap',
  },
  {
    id: 'leisure-entertainment-s10',
    factorId: 'leisure-entertainment',
    title: 'Entertainment',
    description: 'Share something entertaining with a friend.',
    impact: 66,
    category: 'ideal-gap',
  },
  {
    id: 'leisure-hobbies-s1',
    factorId: 'leisure-hobbies',
    title: 'Hobbies',
    description: 'Spend 30 minutes on a hobby.',
    impact: 63,
    category: 'ideal-gap',
  },
  {
    id: 'leisure-hobbies-s2',
    factorId: 'leisure-hobbies',
    title: 'Hobbies',
    description: 'Restart a hobby you paused.',
    impact: 64,
    category: 'ideal-gap',
  },
  {
    id: 'leisure-hobbies-s3',
    factorId: 'leisure-hobbies',
    title: 'Hobbies',
    description: 'Try a new hobby activity.',
    impact: 62,
    category: 'ideal-gap',
  },
  {
    id: 'leisure-hobbies-s4',
    factorId: 'leisure-hobbies',
    title: 'Hobbies',
    description: 'Join a hobby community.',
    impact: 63,
    category: 'ideal-gap',
  },
  {
    id: 'leisure-hobbies-s5',
    factorId: 'leisure-hobbies',
    title: 'Hobbies',
    description: 'Schedule hobby time this weekend.',
    impact: 74,
    category: 'ideal-gap',
  },
  {
    id: 'leisure-hobbies-s6',
    factorId: 'leisure-hobbies',
    title: 'Hobbies',
    description: 'Buy or prepare hobby materials.',
    impact: 62,
    category: 'ideal-gap',
  },
  {
    id: 'leisure-hobbies-s7',
    factorId: 'leisure-hobbies',
    title: 'Hobbies',
    description: 'Watch a tutorial for your hobby.',
    impact: 63,
    category: 'ideal-gap',
  },
  {
    id: 'leisure-hobbies-s8',
    factorId: 'leisure-hobbies',
    title: 'Hobbies',
    description: 'Share your hobby with someone.',
    impact: 68,
    category: 'ideal-gap',
  },
  {
    id: 'leisure-hobbies-s9',
    factorId: 'leisure-hobbies',
    title: 'Hobbies',
    description: 'Practice improving your hobby skill.',
    impact: 62,
    category: 'ideal-gap',
  },
  {
    id: 'leisure-hobbies-s10',
    factorId: 'leisure-hobbies',
    title: 'Hobbies',
    description: 'Create something small.',
    impact: 63,
    category: 'ideal-gap',
  },
  {
    id: 'leisure-social-outings-s1',
    factorId: 'leisure-social-outings',
    title: 'Social outings',
    description: 'Invite someone for coffee.',
    impact: 63,
    category: 'ideal-gap',
  },
  {
    id: 'leisure-social-outings-s2',
    factorId: 'leisure-social-outings',
    title: 'Social outings',
    description: 'Plan a lunch or dinner outing.',
    impact: 73,
    category: 'ideal-gap',
  },
  {
    id: 'leisure-social-outings-s3',
    factorId: 'leisure-social-outings',
    title: 'Social outings',
    description: 'Attend a meetup.',
    impact: 62,
    category: 'ideal-gap',
  },
  {
    id: 'leisure-social-outings-s4',
    factorId: 'leisure-social-outings',
    title: 'Social outings',
    description: 'Go to a city event.',
    impact: 63,
    category: 'ideal-gap',
  },
  {
    id: 'leisure-social-outings-s5',
    factorId: 'leisure-social-outings',
    title: 'Social outings',
    description: 'Take a walk with a friend.',
    impact: 72,
    category: 'ideal-gap',
  },
  {
    id: 'leisure-social-outings-s6',
    factorId: 'leisure-social-outings',
    title: 'Social outings',
    description: 'Visit a café together.',
    impact: 62,
    category: 'ideal-gap',
  },
  {
    id: 'leisure-social-outings-s7',
    factorId: 'leisure-social-outings',
    title: 'Social outings',
    description: 'Attend a cultural event.',
    impact: 63,
    category: 'ideal-gap',
  },
  {
    id: 'leisure-social-outings-s8',
    factorId: 'leisure-social-outings',
    title: 'Social outings',
    description: 'Organize a group hangout.',
    impact: 64,
    category: 'ideal-gap',
  },
  {
    id: 'leisure-social-outings-s9',
    factorId: 'leisure-social-outings',
    title: 'Social outings',
    description: 'Explore a new place with someone.',
    impact: 62,
    category: 'ideal-gap',
  },
  {
    id: 'leisure-social-outings-s10',
    factorId: 'leisure-social-outings',
    title: 'Social outings',
    description: 'Join a social activity group.',
    impact: 63,
    category: 'ideal-gap',
  },
  {
    id: 'leisure-travel-exploration-s1',
    factorId: 'leisure-travel-exploration',
    title: 'Travel / exploration',
    description: 'Visit a new place in your city.',
    impact: 63,
    category: 'ideal-gap',
  },
  {
    id: 'leisure-travel-exploration-s2',
    factorId: 'leisure-travel-exploration',
    title: 'Travel / exploration',
    description: 'Take a day trip nearby.',
    impact: 64,
    category: 'ideal-gap',
  },
  {
    id: 'leisure-travel-exploration-s3',
    factorId: 'leisure-travel-exploration',
    title: 'Travel / exploration',
    description: 'Research a travel destination.',
    impact: 62,
    category: 'ideal-gap',
  },
  {
    id: 'leisure-travel-exploration-s4',
    factorId: 'leisure-travel-exploration',
    title: 'Travel / exploration',
    description: 'Explore a park or nature area.',
    impact: 63,
    category: 'ideal-gap',
  },
  {
    id: 'leisure-travel-exploration-s5',
    factorId: 'leisure-travel-exploration',
    title: 'Travel / exploration',
    description: 'Walk a new neighborhood.',
    impact: 72,
    category: 'ideal-gap',
  },
  {
    id: 'leisure-travel-exploration-s6',
    factorId: 'leisure-travel-exploration',
    title: 'Travel / exploration',
    description: 'Try food from another culture.',
    impact: 62,
    category: 'ideal-gap',
  },
  {
    id: 'leisure-travel-exploration-s7',
    factorId: 'leisure-travel-exploration',
    title: 'Travel / exploration',
    description: 'Look up travel experiences.',
    impact: 63,
    category: 'ideal-gap',
  },
  {
    id: 'leisure-travel-exploration-s8',
    factorId: 'leisure-travel-exploration',
    title: 'Travel / exploration',
    description: 'Plan a weekend getaway.',
    impact: 73,
    category: 'ideal-gap',
  },
  {
    id: 'leisure-travel-exploration-s9',
    factorId: 'leisure-travel-exploration',
    title: 'Travel / exploration',
    description: 'Visit a museum or gallery.',
    impact: 62,
    category: 'ideal-gap',
  },
  {
    id: 'leisure-travel-exploration-s10',
    factorId: 'leisure-travel-exploration',
    title: 'Travel / exploration',
    description: 'Take photos while exploring.',
    impact: 63,
    category: 'ideal-gap',
  },
  {
    id: 'relationships-community-belonging-s1',
    factorId: 'relationships-community-belonging',
    title: 'Community / belonging',
    description: 'Attend a local meetup or community event.',
    impact: 64,
    category: 'ideal-gap',
  },
  {
    id: 'relationships-community-belonging-s2',
    factorId: 'relationships-community-belonging',
    title: 'Community / belonging',
    description: 'Join a group around a shared interest.',
    impact: 69,
    category: 'ideal-gap',
  },
  {
    id: 'relationships-community-belonging-s3',
    factorId: 'relationships-community-belonging',
    title: 'Community / belonging',
    description: 'Volunteer for a local cause.',
    impact: 71,
    category: 'ideal-gap',
  },
  {
    id: 'relationships-community-belonging-s4',
    factorId: 'relationships-community-belonging',
    title: 'Community / belonging',
    description: 'Participate in a community discussion.',
    impact: 64,
    category: 'ideal-gap',
  },
  {
    id: 'relationships-community-belonging-s5',
    factorId: 'relationships-community-belonging',
    title: 'Community / belonging',
    description: 'Introduce yourself to someone new in a group.',
    impact: 65,
    category: 'ideal-gap',
  },
  {
    id: 'relationships-community-belonging-s6',
    factorId: 'relationships-community-belonging',
    title: 'Community / belonging',
    description: 'Support a community project.',
    impact: 63,
    category: 'ideal-gap',
  },
  {
    id: 'relationships-community-belonging-s7',
    factorId: 'relationships-community-belonging',
    title: 'Community / belonging',
    description: 'Help organize a small gathering.',
    impact: 64,
    category: 'ideal-gap',
  },
  {
    id: 'relationships-community-belonging-s8',
    factorId: 'relationships-community-belonging',
    title: 'Community / belonging',
    description: 'Reconnect with a group you used to attend.',
    impact: 65,
    category: 'ideal-gap',
  },
  {
    id: 'relationships-community-belonging-s9',
    factorId: 'relationships-community-belonging',
    title: 'Community / belonging',
    description: 'Attend a workshop or talk.',
    impact: 67,
    category: 'ideal-gap',
  },
  {
    id: 'relationships-community-belonging-s10',
    factorId: 'relationships-community-belonging',
    title: 'Community / belonging',
    description: 'Offer help to someone in your community.',
    impact: 64,
    category: 'ideal-gap',
  },
  {
    id: 'relationships-family-connection-s1',
    factorId: 'relationships-family-connection',
    title: 'Family connection',
    description: 'Call a family member you haven\'t spoken to in a while.',
    impact: 70,
    category: 'ideal-gap',
  },
  {
    id: 'relationships-family-connection-s2',
    factorId: 'relationships-family-connection',
    title: 'Family connection',
    description: 'Plan a family dinner or meal together.',
    impact: 76,
    category: 'ideal-gap',
  },
  {
    id: 'relationships-family-connection-s3',
    factorId: 'relationships-family-connection',
    title: 'Family connection',
    description: 'Send a thoughtful message thanking a family member.',
    impact: 69,
    category: 'ideal-gap',
  },
  {
    id: 'relationships-family-connection-s4',
    factorId: 'relationships-family-connection',
    title: 'Family connection',
    description: 'Ask a family member about something important in their life.',
    impact: 70,
    category: 'ideal-gap',
  },
  {
    id: 'relationships-family-connection-s5',
    factorId: 'relationships-family-connection',
    title: 'Family connection',
    description: 'Share a photo or memory with a family member.',
    impact: 71,
    category: 'ideal-gap',
  },
  {
    id: 'relationships-family-connection-s6',
    factorId: 'relationships-family-connection',
    title: 'Family connection',
    description: 'Offer help with something a family member needs.',
    impact: 65,
    category: 'ideal-gap',
  },
  {
    id: 'relationships-family-connection-s7',
    factorId: 'relationships-family-connection',
    title: 'Family connection',
    description: 'Plan a short walk or coffee with a relative.',
    impact: 86,
    category: 'ideal-gap',
  },
  {
    id: 'relationships-family-connection-s8',
    factorId: 'relationships-family-connection',
    title: 'Family connection',
    description: 'Set a weekly reminder to check in with family.',
    impact: 77,
    category: 'ideal-gap',
  },
  {
    id: 'relationships-family-connection-s9',
    factorId: 'relationships-family-connection',
    title: 'Family connection',
    description: 'Ask deeper questions during your next conversation.',
    impact: 69,
    category: 'ideal-gap',
  },
  {
    id: 'relationships-family-connection-s10',
    factorId: 'relationships-family-connection',
    title: 'Family connection',
    description: 'Resolve a small misunderstanding or tension.',
    impact: 74,
    category: 'ideal-gap',
  },
  {
    id: 'relationships-friendships-s1',
    factorId: 'relationships-friendships',
    title: 'Friendships',
    description: 'Send a quick message to a friend to check in.',
    impact: 72,
    category: 'ideal-gap',
  },
  {
    id: 'relationships-friendships-s2',
    factorId: 'relationships-friendships',
    title: 'Friendships',
    description: 'Invite a friend for coffee or a walk.',
    impact: 74,
    category: 'ideal-gap',
  },
  {
    id: 'relationships-friendships-s3',
    factorId: 'relationships-friendships',
    title: 'Friendships',
    description: 'Reconnect with an old friend.',
    impact: 64,
    category: 'ideal-gap',
  },
  {
    id: 'relationships-friendships-s4',
    factorId: 'relationships-friendships',
    title: 'Friendships',
    description: 'Plan a monthly meetup with friends.',
    impact: 84,
    category: 'ideal-gap',
  },
  {
    id: 'relationships-friendships-s5',
    factorId: 'relationships-friendships',
    title: 'Friendships',
    description: 'Share something funny or interesting with a friend.',
    impact: 70,
    category: 'ideal-gap',
  },
  {
    id: 'relationships-friendships-s6',
    factorId: 'relationships-friendships',
    title: 'Friendships',
    description: 'Celebrate a friend\'s small win.',
    impact: 64,
    category: 'ideal-gap',
  },
  {
    id: 'relationships-friendships-s7',
    factorId: 'relationships-friendships',
    title: 'Friendships',
    description: 'Ask a friend for their perspective on something.',
    impact: 69,
    category: 'ideal-gap',
  },
  {
    id: 'relationships-friendships-s8',
    factorId: 'relationships-friendships',
    title: 'Friendships',
    description: 'Introduce two friends who might get along.',
    impact: 66,
    category: 'ideal-gap',
  },
  {
    id: 'relationships-friendships-s9',
    factorId: 'relationships-friendships',
    title: 'Friendships',
    description: 'Attend an event with a friend.',
    impact: 64,
    category: 'ideal-gap',
  },
  {
    id: 'relationships-friendships-s10',
    factorId: 'relationships-friendships',
    title: 'Friendships',
    description: 'Schedule a 30‑minute catch‑up call.',
    impact: 79,
    category: 'ideal-gap',
  },
  {
    id: 'relationships-romantic-intimacy-s1',
    factorId: 'relationships-romantic-intimacy',
    title: 'Romantic / intimacy',
    description: 'Plan a simple date night.',
    impact: 75,
    category: 'ideal-gap',
  },
  {
    id: 'relationships-romantic-intimacy-s2',
    factorId: 'relationships-romantic-intimacy',
    title: 'Romantic / intimacy',
    description: 'Express appreciation to your partner.',
    impact: 67,
    category: 'ideal-gap',
  },
  {
    id: 'relationships-romantic-intimacy-s3',
    factorId: 'relationships-romantic-intimacy',
    title: 'Romantic / intimacy',
    description: 'Spend 30 minutes talking without phones.',
    impact: 69,
    category: 'ideal-gap',
  },
  {
    id: 'relationships-romantic-intimacy-s4',
    factorId: 'relationships-romantic-intimacy',
    title: 'Romantic / intimacy',
    description: 'Do a small act of kindness for your partner.',
    impact: 66,
    category: 'ideal-gap',
  },
  {
    id: 'relationships-romantic-intimacy-s5',
    factorId: 'relationships-romantic-intimacy',
    title: 'Romantic / intimacy',
    description: 'Ask your partner about something meaningful.',
    impact: 71,
    category: 'ideal-gap',
  },
  {
    id: 'relationships-romantic-intimacy-s6',
    factorId: 'relationships-romantic-intimacy',
    title: 'Romantic / intimacy',
    description: 'Share something vulnerable.',
    impact: 69,
    category: 'ideal-gap',
  },
  {
    id: 'relationships-romantic-intimacy-s7',
    factorId: 'relationships-romantic-intimacy',
    title: 'Romantic / intimacy',
    description: 'Take a walk together.',
    impact: 74,
    category: 'ideal-gap',
  },
  {
    id: 'relationships-romantic-intimacy-s8',
    factorId: 'relationships-romantic-intimacy',
    title: 'Romantic / intimacy',
    description: 'Cook or order dinner together intentionally.',
    impact: 67,
    category: 'ideal-gap',
  },
  {
    id: 'relationships-romantic-intimacy-s9',
    factorId: 'relationships-romantic-intimacy',
    title: 'Romantic / intimacy',
    description: 'Give a genuine compliment.',
    impact: 65,
    category: 'ideal-gap',
  },
  {
    id: 'relationships-romantic-intimacy-s10',
    factorId: 'relationships-romantic-intimacy',
    title: 'Romantic / intimacy',
    description: 'Discuss one thing you\'d like to improve together.',
    impact: 74,
    category: 'ideal-gap',
  },
]

export const SUGGESTIONS_BY_FACTOR = SUGGESTION_POOL.reduce<Record<string, Suggestion[]>>(
  (acc, suggestion) => {
    const list = acc[suggestion.factorId] ?? []
    list.push(suggestion)
    acc[suggestion.factorId] = list
    return acc
  },
  {},
)
