import { Suggestion } from '../types'

export const SUGGESTION_POOL: Suggestion[] = [
  {
    id: 'relationships-family-connection-s1',
    factorId: 'relationships-family-connection',
    title: 'Family connection',
    description: 'Schedule a dedicated 30-minute block this week focused on this area.',
    impact: 77,
    category: 'ideal-gap',
  },
  {
    id: 'relationships-family-connection-s2',
    factorId: 'relationships-family-connection',
    title: 'Family connection',
    description: 'Have a meaningful conversation with someone connected to this area.',
    impact: 93,
    category: 'ideal-gap',
  },
  {
    id: 'relationships-family-connection-s3',
    factorId: 'relationships-family-connection',
    title: 'Family connection',
    description: 'Remove one friction point that makes this area harder than it should be.',
    impact: 78,
    category: 'ideal-gap',
  },
  {
    id: 'relationships-family-connection-s4',
    factorId: 'relationships-family-connection',
    title: 'Family connection',
    description: 'Create a simple weekly habit that supports this factor.',
    impact: 93,
    category: 'ideal-gap',
  },
  {
    id: 'relationships-family-connection-s5',
    factorId: 'relationships-family-connection',
    title: 'Family connection',
    description: 'Track your progress for the next 7 days.',
    impact: 66,
    category: 'ideal-gap',
  },
  {
    id: 'relationships-family-connection-s6',
    factorId: 'relationships-family-connection',
    title: 'Family connection',
    description: 'Spend 20 minutes learning something new related to this area.',
    impact: 88,
    category: 'ideal-gap',
  },
  {
    id: 'relationships-family-connection-s7',
    factorId: 'relationships-family-connection',
    title: 'Family connection',
    description: 'Plan a small activity this weekend that improves this factor.',
    impact: 93,
    category: 'ideal-gap',
  },
  {
    id: 'relationships-family-connection-s8',
    factorId: 'relationships-family-connection',
    title: 'Family connection',
    description: 'Reflect for 10 minutes on what has helped or harmed this area recently.',
    impact: 67,
    category: 'ideal-gap',
  },
  {
    id: 'relationships-family-connection-s9',
    factorId: 'relationships-family-connection',
    title: 'Family connection',
    description: 'Set a realistic improvement goal for the next month.',
    impact: 95,
    category: 'ideal-gap',
  },
  {
    id: 'relationships-family-connection-s10',
    factorId: 'relationships-family-connection',
    title: 'Family connection',
    description: 'Experiment with one new approach or routine related to this factor.',
    impact: 81,
    category: 'ideal-gap',
  },
  {
    id: 'relationships-friendships-s1',
    factorId: 'relationships-friendships',
    title: 'Friendships',
    description: 'Schedule a dedicated 30-minute block this week focused on this area.',
    impact: 92,
    category: 'ideal-gap',
  },
  {
    id: 'relationships-friendships-s2',
    factorId: 'relationships-friendships',
    title: 'Friendships',
    description: 'Have a meaningful conversation with someone connected to this area.',
    impact: 92,
    category: 'ideal-gap',
  },
  {
    id: 'relationships-friendships-s3',
    factorId: 'relationships-friendships',
    title: 'Friendships',
    description: 'Remove one friction point that makes this area harder than it should be.',
    impact: 70,
    category: 'ideal-gap',
  },
  {
    id: 'relationships-friendships-s4',
    factorId: 'relationships-friendships',
    title: 'Friendships',
    description: 'Create a simple weekly habit that supports this factor.',
    impact: 80,
    category: 'ideal-gap',
  },
  {
    id: 'relationships-friendships-s5',
    factorId: 'relationships-friendships',
    title: 'Friendships',
    description: 'Track your progress for the next 7 days.',
    impact: 82,
    category: 'ideal-gap',
  },
  {
    id: 'relationships-friendships-s6',
    factorId: 'relationships-friendships',
    title: 'Friendships',
    description: 'Spend 20 minutes learning something new related to this area.',
    impact: 91,
    category: 'ideal-gap',
  },
  {
    id: 'relationships-friendships-s7',
    factorId: 'relationships-friendships',
    title: 'Friendships',
    description: 'Plan a small activity this weekend that improves this factor.',
    impact: 75,
    category: 'ideal-gap',
  },
  {
    id: 'relationships-friendships-s8',
    factorId: 'relationships-friendships',
    title: 'Friendships',
    description: 'Reflect for 10 minutes on what has helped or harmed this area recently.',
    impact: 73,
    category: 'ideal-gap',
  },
  {
    id: 'relationships-friendships-s9',
    factorId: 'relationships-friendships',
    title: 'Friendships',
    description: 'Set a realistic improvement goal for the next month.',
    impact: 60,
    category: 'ideal-gap',
  },
  {
    id: 'relationships-friendships-s10',
    factorId: 'relationships-friendships',
    title: 'Friendships',
    description: 'Experiment with one new approach or routine related to this factor.',
    impact: 62,
    category: 'ideal-gap',
  },
  {
    id: 'relationships-romantic-intimacy-s1',
    factorId: 'relationships-romantic-intimacy',
    title: 'Romantic / intimacy',
    description: 'Schedule a dedicated 30-minute block this week focused on this area.',
    impact: 76,
    category: 'ideal-gap',
  },
  {
    id: 'relationships-romantic-intimacy-s2',
    factorId: 'relationships-romantic-intimacy',
    title: 'Romantic / intimacy',
    description: 'Have a meaningful conversation with someone connected to this area.',
    impact: 75,
    category: 'ideal-gap',
  },
  {
    id: 'relationships-romantic-intimacy-s3',
    factorId: 'relationships-romantic-intimacy',
    title: 'Romantic / intimacy',
    description: 'Remove one friction point that makes this area harder than it should be.',
    impact: 79,
    category: 'ideal-gap',
  },
  {
    id: 'relationships-romantic-intimacy-s4',
    factorId: 'relationships-romantic-intimacy',
    title: 'Romantic / intimacy',
    description: 'Create a simple weekly habit that supports this factor.',
    impact: 84,
    category: 'ideal-gap',
  },
  {
    id: 'relationships-romantic-intimacy-s5',
    factorId: 'relationships-romantic-intimacy',
    title: 'Romantic / intimacy',
    description: 'Track your progress for the next 7 days.',
    impact: 69,
    category: 'ideal-gap',
  },
  {
    id: 'relationships-romantic-intimacy-s6',
    factorId: 'relationships-romantic-intimacy',
    title: 'Romantic / intimacy',
    description: 'Spend 20 minutes learning something new related to this area.',
    impact: 71,
    category: 'ideal-gap',
  },
  {
    id: 'relationships-romantic-intimacy-s7',
    factorId: 'relationships-romantic-intimacy',
    title: 'Romantic / intimacy',
    description: 'Plan a small activity this weekend that improves this factor.',
    impact: 94,
    category: 'ideal-gap',
  },
  {
    id: 'relationships-romantic-intimacy-s8',
    factorId: 'relationships-romantic-intimacy',
    title: 'Romantic / intimacy',
    description: 'Reflect for 10 minutes on what has helped or harmed this area recently.',
    impact: 83,
    category: 'ideal-gap',
  },
  {
    id: 'relationships-romantic-intimacy-s9',
    factorId: 'relationships-romantic-intimacy',
    title: 'Romantic / intimacy',
    description: 'Set a realistic improvement goal for the next month.',
    impact: 84,
    category: 'ideal-gap',
  },
  {
    id: 'relationships-romantic-intimacy-s10',
    factorId: 'relationships-romantic-intimacy',
    title: 'Romantic / intimacy',
    description: 'Experiment with one new approach or routine related to this factor.',
    impact: 82,
    category: 'ideal-gap',
  },
  {
    id: 'relationships-community-belonging-s1',
    factorId: 'relationships-community-belonging',
    title: 'Community / belonging',
    description: 'Schedule a dedicated 30-minute block this week focused on this area.',
    impact: 63,
    category: 'ideal-gap',
  },
  {
    id: 'relationships-community-belonging-s2',
    factorId: 'relationships-community-belonging',
    title: 'Community / belonging',
    description: 'Have a meaningful conversation with someone connected to this area.',
    impact: 80,
    category: 'ideal-gap',
  },
  {
    id: 'relationships-community-belonging-s3',
    factorId: 'relationships-community-belonging',
    title: 'Community / belonging',
    description: 'Remove one friction point that makes this area harder than it should be.',
    impact: 81,
    category: 'ideal-gap',
  },
  {
    id: 'relationships-community-belonging-s4',
    factorId: 'relationships-community-belonging',
    title: 'Community / belonging',
    description: 'Create a simple weekly habit that supports this factor.',
    impact: 91,
    category: 'ideal-gap',
  },
  {
    id: 'relationships-community-belonging-s5',
    factorId: 'relationships-community-belonging',
    title: 'Community / belonging',
    description: 'Track your progress for the next 7 days.',
    impact: 69,
    category: 'ideal-gap',
  },
  {
    id: 'relationships-community-belonging-s6',
    factorId: 'relationships-community-belonging',
    title: 'Community / belonging',
    description: 'Spend 20 minutes learning something new related to this area.',
    impact: 81,
    category: 'ideal-gap',
  },
  {
    id: 'relationships-community-belonging-s7',
    factorId: 'relationships-community-belonging',
    title: 'Community / belonging',
    description: 'Plan a small activity this weekend that improves this factor.',
    impact: 65,
    category: 'ideal-gap',
  },
  {
    id: 'relationships-community-belonging-s8',
    factorId: 'relationships-community-belonging',
    title: 'Community / belonging',
    description: 'Reflect for 10 minutes on what has helped or harmed this area recently.',
    impact: 78,
    category: 'ideal-gap',
  },
  {
    id: 'relationships-community-belonging-s9',
    factorId: 'relationships-community-belonging',
    title: 'Community / belonging',
    description: 'Set a realistic improvement goal for the next month.',
    impact: 92,
    category: 'ideal-gap',
  },
  {
    id: 'relationships-community-belonging-s10',
    factorId: 'relationships-community-belonging',
    title: 'Community / belonging',
    description: 'Experiment with one new approach or routine related to this factor.',
    impact: 81,
    category: 'ideal-gap',
  },
  {
    id: 'health-physical-activity-s1',
    factorId: 'health-physical-activity',
    title: 'Physical activity',
    description: 'Schedule a dedicated 30-minute block this week focused on this area.',
    impact: 61,
    category: 'ideal-gap',
  },
  {
    id: 'health-physical-activity-s2',
    factorId: 'health-physical-activity',
    title: 'Physical activity',
    description: 'Have a meaningful conversation with someone connected to this area.',
    impact: 85,
    category: 'ideal-gap',
  },
  {
    id: 'health-physical-activity-s3',
    factorId: 'health-physical-activity',
    title: 'Physical activity',
    description: 'Remove one friction point that makes this area harder than it should be.',
    impact: 79,
    category: 'ideal-gap',
  },
  {
    id: 'health-physical-activity-s4',
    factorId: 'health-physical-activity',
    title: 'Physical activity',
    description: 'Create a simple weekly habit that supports this factor.',
    impact: 83,
    category: 'ideal-gap',
  },
  {
    id: 'health-physical-activity-s5',
    factorId: 'health-physical-activity',
    title: 'Physical activity',
    description: 'Track your progress for the next 7 days.',
    impact: 63,
    category: 'ideal-gap',
  },
  {
    id: 'health-physical-activity-s6',
    factorId: 'health-physical-activity',
    title: 'Physical activity',
    description: 'Spend 20 minutes learning something new related to this area.',
    impact: 75,
    category: 'ideal-gap',
  },
  {
    id: 'health-physical-activity-s7',
    factorId: 'health-physical-activity',
    title: 'Physical activity',
    description: 'Plan a small activity this weekend that improves this factor.',
    impact: 67,
    category: 'ideal-gap',
  },
  {
    id: 'health-physical-activity-s8',
    factorId: 'health-physical-activity',
    title: 'Physical activity',
    description: 'Reflect for 10 minutes on what has helped or harmed this area recently.',
    impact: 65,
    category: 'ideal-gap',
  },
  {
    id: 'health-physical-activity-s9',
    factorId: 'health-physical-activity',
    title: 'Physical activity',
    description: 'Set a realistic improvement goal for the next month.',
    impact: 87,
    category: 'ideal-gap',
  },
  {
    id: 'health-physical-activity-s10',
    factorId: 'health-physical-activity',
    title: 'Physical activity',
    description: 'Experiment with one new approach or routine related to this factor.',
    impact: 69,
    category: 'ideal-gap',
  },
  {
    id: 'health-nutrition-s1',
    factorId: 'health-nutrition',
    title: 'Nutrition',
    description: 'Schedule a dedicated 30-minute block this week focused on this area.',
    impact: 82,
    category: 'ideal-gap',
  },
  {
    id: 'health-nutrition-s2',
    factorId: 'health-nutrition',
    title: 'Nutrition',
    description: 'Have a meaningful conversation with someone connected to this area.',
    impact: 68,
    category: 'ideal-gap',
  },
  {
    id: 'health-nutrition-s3',
    factorId: 'health-nutrition',
    title: 'Nutrition',
    description: 'Remove one friction point that makes this area harder than it should be.',
    impact: 77,
    category: 'ideal-gap',
  },
  {
    id: 'health-nutrition-s4',
    factorId: 'health-nutrition',
    title: 'Nutrition',
    description: 'Create a simple weekly habit that supports this factor.',
    impact: 86,
    category: 'ideal-gap',
  },
  {
    id: 'health-nutrition-s5',
    factorId: 'health-nutrition',
    title: 'Nutrition',
    description: 'Track your progress for the next 7 days.',
    impact: 95,
    category: 'ideal-gap',
  },
  {
    id: 'health-nutrition-s6',
    factorId: 'health-nutrition',
    title: 'Nutrition',
    description: 'Spend 20 minutes learning something new related to this area.',
    impact: 67,
    category: 'ideal-gap',
  },
  {
    id: 'health-nutrition-s7',
    factorId: 'health-nutrition',
    title: 'Nutrition',
    description: 'Plan a small activity this weekend that improves this factor.',
    impact: 86,
    category: 'ideal-gap',
  },
  {
    id: 'health-nutrition-s8',
    factorId: 'health-nutrition',
    title: 'Nutrition',
    description: 'Reflect for 10 minutes on what has helped or harmed this area recently.',
    impact: 67,
    category: 'ideal-gap',
  },
  {
    id: 'health-nutrition-s9',
    factorId: 'health-nutrition',
    title: 'Nutrition',
    description: 'Set a realistic improvement goal for the next month.',
    impact: 87,
    category: 'ideal-gap',
  },
  {
    id: 'health-nutrition-s10',
    factorId: 'health-nutrition',
    title: 'Nutrition',
    description: 'Experiment with one new approach or routine related to this factor.',
    impact: 92,
    category: 'ideal-gap',
  },
  {
    id: 'health-sleep-quality-s1',
    factorId: 'health-sleep-quality',
    title: 'Sleep quality',
    description: 'Schedule a dedicated 30-minute block this week focused on this area.',
    impact: 63,
    category: 'ideal-gap',
  },
  {
    id: 'health-sleep-quality-s2',
    factorId: 'health-sleep-quality',
    title: 'Sleep quality',
    description: 'Have a meaningful conversation with someone connected to this area.',
    impact: 92,
    category: 'ideal-gap',
  },
  {
    id: 'health-sleep-quality-s3',
    factorId: 'health-sleep-quality',
    title: 'Sleep quality',
    description: 'Remove one friction point that makes this area harder than it should be.',
    impact: 72,
    category: 'ideal-gap',
  },
  {
    id: 'health-sleep-quality-s4',
    factorId: 'health-sleep-quality',
    title: 'Sleep quality',
    description: 'Create a simple weekly habit that supports this factor.',
    impact: 89,
    category: 'ideal-gap',
  },
  {
    id: 'health-sleep-quality-s5',
    factorId: 'health-sleep-quality',
    title: 'Sleep quality',
    description: 'Track your progress for the next 7 days.',
    impact: 89,
    category: 'ideal-gap',
  },
  {
    id: 'health-sleep-quality-s6',
    factorId: 'health-sleep-quality',
    title: 'Sleep quality',
    description: 'Spend 20 minutes learning something new related to this area.',
    impact: 69,
    category: 'ideal-gap',
  },
  {
    id: 'health-sleep-quality-s7',
    factorId: 'health-sleep-quality',
    title: 'Sleep quality',
    description: 'Plan a small activity this weekend that improves this factor.',
    impact: 81,
    category: 'ideal-gap',
  },
  {
    id: 'health-sleep-quality-s8',
    factorId: 'health-sleep-quality',
    title: 'Sleep quality',
    description: 'Reflect for 10 minutes on what has helped or harmed this area recently.',
    impact: 67,
    category: 'ideal-gap',
  },
  {
    id: 'health-sleep-quality-s9',
    factorId: 'health-sleep-quality',
    title: 'Sleep quality',
    description: 'Set a realistic improvement goal for the next month.',
    impact: 81,
    category: 'ideal-gap',
  },
  {
    id: 'health-sleep-quality-s10',
    factorId: 'health-sleep-quality',
    title: 'Sleep quality',
    description: 'Experiment with one new approach or routine related to this factor.',
    impact: 85,
    category: 'ideal-gap',
  },
  {
    id: 'health-mental-well-being-s1',
    factorId: 'health-mental-well-being',
    title: 'Mental well-being',
    description: 'Schedule a dedicated 30-minute block this week focused on this area.',
    impact: 77,
    category: 'ideal-gap',
  },
  {
    id: 'health-mental-well-being-s2',
    factorId: 'health-mental-well-being',
    title: 'Mental well-being',
    description: 'Have a meaningful conversation with someone connected to this area.',
    impact: 80,
    category: 'ideal-gap',
  },
  {
    id: 'health-mental-well-being-s3',
    factorId: 'health-mental-well-being',
    title: 'Mental well-being',
    description: 'Remove one friction point that makes this area harder than it should be.',
    impact: 61,
    category: 'ideal-gap',
  },
  {
    id: 'health-mental-well-being-s4',
    factorId: 'health-mental-well-being',
    title: 'Mental well-being',
    description: 'Create a simple weekly habit that supports this factor.',
    impact: 94,
    category: 'ideal-gap',
  },
  {
    id: 'health-mental-well-being-s5',
    factorId: 'health-mental-well-being',
    title: 'Mental well-being',
    description: 'Track your progress for the next 7 days.',
    impact: 81,
    category: 'ideal-gap',
  },
  {
    id: 'health-mental-well-being-s6',
    factorId: 'health-mental-well-being',
    title: 'Mental well-being',
    description: 'Spend 20 minutes learning something new related to this area.',
    impact: 75,
    category: 'ideal-gap',
  },
  {
    id: 'health-mental-well-being-s7',
    factorId: 'health-mental-well-being',
    title: 'Mental well-being',
    description: 'Plan a small activity this weekend that improves this factor.',
    impact: 83,
    category: 'ideal-gap',
  },
  {
    id: 'health-mental-well-being-s8',
    factorId: 'health-mental-well-being',
    title: 'Mental well-being',
    description: 'Reflect for 10 minutes on what has helped or harmed this area recently.',
    impact: 81,
    category: 'ideal-gap',
  },
  {
    id: 'health-mental-well-being-s9',
    factorId: 'health-mental-well-being',
    title: 'Mental well-being',
    description: 'Set a realistic improvement goal for the next month.',
    impact: 81,
    category: 'ideal-gap',
  },
  {
    id: 'health-mental-well-being-s10',
    factorId: 'health-mental-well-being',
    title: 'Mental well-being',
    description: 'Experiment with one new approach or routine related to this factor.',
    impact: 77,
    category: 'ideal-gap',
  },
  {
    id: 'career-job-work-satisfaction-s1',
    factorId: 'career-job-work-satisfaction',
    title: 'Job / work satisfaction',
    description: 'Schedule a dedicated 30-minute block this week focused on this area.',
    impact: 65,
    category: 'ideal-gap',
  },
  {
    id: 'career-job-work-satisfaction-s2',
    factorId: 'career-job-work-satisfaction',
    title: 'Job / work satisfaction',
    description: 'Have a meaningful conversation with someone connected to this area.',
    impact: 60,
    category: 'ideal-gap',
  },
  {
    id: 'career-job-work-satisfaction-s3',
    factorId: 'career-job-work-satisfaction',
    title: 'Job / work satisfaction',
    description: 'Remove one friction point that makes this area harder than it should be.',
    impact: 86,
    category: 'ideal-gap',
  },
  {
    id: 'career-job-work-satisfaction-s4',
    factorId: 'career-job-work-satisfaction',
    title: 'Job / work satisfaction',
    description: 'Create a simple weekly habit that supports this factor.',
    impact: 81,
    category: 'ideal-gap',
  },
  {
    id: 'career-job-work-satisfaction-s5',
    factorId: 'career-job-work-satisfaction',
    title: 'Job / work satisfaction',
    description: 'Track your progress for the next 7 days.',
    impact: 88,
    category: 'ideal-gap',
  },
  {
    id: 'career-job-work-satisfaction-s6',
    factorId: 'career-job-work-satisfaction',
    title: 'Job / work satisfaction',
    description: 'Spend 20 minutes learning something new related to this area.',
    impact: 65,
    category: 'ideal-gap',
  },
  {
    id: 'career-job-work-satisfaction-s7',
    factorId: 'career-job-work-satisfaction',
    title: 'Job / work satisfaction',
    description: 'Plan a small activity this weekend that improves this factor.',
    impact: 93,
    category: 'ideal-gap',
  },
  {
    id: 'career-job-work-satisfaction-s8',
    factorId: 'career-job-work-satisfaction',
    title: 'Job / work satisfaction',
    description: 'Reflect for 10 minutes on what has helped or harmed this area recently.',
    impact: 76,
    category: 'ideal-gap',
  },
  {
    id: 'career-job-work-satisfaction-s9',
    factorId: 'career-job-work-satisfaction',
    title: 'Job / work satisfaction',
    description: 'Set a realistic improvement goal for the next month.',
    impact: 88,
    category: 'ideal-gap',
  },
  {
    id: 'career-job-work-satisfaction-s10',
    factorId: 'career-job-work-satisfaction',
    title: 'Job / work satisfaction',
    description: 'Experiment with one new approach or routine related to this factor.',
    impact: 88,
    category: 'ideal-gap',
  },
  {
    id: 'career-personal-projects-s1',
    factorId: 'career-personal-projects',
    title: 'Personal projects',
    description: 'Schedule a dedicated 30-minute block this week focused on this area.',
    impact: 82,
    category: 'ideal-gap',
  },
  {
    id: 'career-personal-projects-s2',
    factorId: 'career-personal-projects',
    title: 'Personal projects',
    description: 'Have a meaningful conversation with someone connected to this area.',
    impact: 73,
    category: 'ideal-gap',
  },
  {
    id: 'career-personal-projects-s3',
    factorId: 'career-personal-projects',
    title: 'Personal projects',
    description: 'Remove one friction point that makes this area harder than it should be.',
    impact: 61,
    category: 'ideal-gap',
  },
  {
    id: 'career-personal-projects-s4',
    factorId: 'career-personal-projects',
    title: 'Personal projects',
    description: 'Create a simple weekly habit that supports this factor.',
    impact: 65,
    category: 'ideal-gap',
  },
  {
    id: 'career-personal-projects-s5',
    factorId: 'career-personal-projects',
    title: 'Personal projects',
    description: 'Track your progress for the next 7 days.',
    impact: 85,
    category: 'ideal-gap',
  },
  {
    id: 'career-personal-projects-s6',
    factorId: 'career-personal-projects',
    title: 'Personal projects',
    description: 'Spend 20 minutes learning something new related to this area.',
    impact: 76,
    category: 'ideal-gap',
  },
  {
    id: 'career-personal-projects-s7',
    factorId: 'career-personal-projects',
    title: 'Personal projects',
    description: 'Plan a small activity this weekend that improves this factor.',
    impact: 91,
    category: 'ideal-gap',
  },
  {
    id: 'career-personal-projects-s8',
    factorId: 'career-personal-projects',
    title: 'Personal projects',
    description: 'Reflect for 10 minutes on what has helped or harmed this area recently.',
    impact: 87,
    category: 'ideal-gap',
  },
  {
    id: 'career-personal-projects-s9',
    factorId: 'career-personal-projects',
    title: 'Personal projects',
    description: 'Set a realistic improvement goal for the next month.',
    impact: 84,
    category: 'ideal-gap',
  },
  {
    id: 'career-personal-projects-s10',
    factorId: 'career-personal-projects',
    title: 'Personal projects',
    description: 'Experiment with one new approach or routine related to this factor.',
    impact: 76,
    category: 'ideal-gap',
  },
  {
    id: 'career-skill-development-s1',
    factorId: 'career-skill-development',
    title: 'Skill development',
    description: 'Schedule a dedicated 30-minute block this week focused on this area.',
    impact: 87,
    category: 'ideal-gap',
  },
  {
    id: 'career-skill-development-s2',
    factorId: 'career-skill-development',
    title: 'Skill development',
    description: 'Have a meaningful conversation with someone connected to this area.',
    impact: 65,
    category: 'ideal-gap',
  },
  {
    id: 'career-skill-development-s3',
    factorId: 'career-skill-development',
    title: 'Skill development',
    description: 'Remove one friction point that makes this area harder than it should be.',
    impact: 89,
    category: 'ideal-gap',
  },
  {
    id: 'career-skill-development-s4',
    factorId: 'career-skill-development',
    title: 'Skill development',
    description: 'Create a simple weekly habit that supports this factor.',
    impact: 65,
    category: 'ideal-gap',
  },
  {
    id: 'career-skill-development-s5',
    factorId: 'career-skill-development',
    title: 'Skill development',
    description: 'Track your progress for the next 7 days.',
    impact: 63,
    category: 'ideal-gap',
  },
  {
    id: 'career-skill-development-s6',
    factorId: 'career-skill-development',
    title: 'Skill development',
    description: 'Spend 20 minutes learning something new related to this area.',
    impact: 95,
    category: 'ideal-gap',
  },
  {
    id: 'career-skill-development-s7',
    factorId: 'career-skill-development',
    title: 'Skill development',
    description: 'Plan a small activity this weekend that improves this factor.',
    impact: 74,
    category: 'ideal-gap',
  },
  {
    id: 'career-skill-development-s8',
    factorId: 'career-skill-development',
    title: 'Skill development',
    description: 'Reflect for 10 minutes on what has helped or harmed this area recently.',
    impact: 83,
    category: 'ideal-gap',
  },
  {
    id: 'career-skill-development-s9',
    factorId: 'career-skill-development',
    title: 'Skill development',
    description: 'Set a realistic improvement goal for the next month.',
    impact: 94,
    category: 'ideal-gap',
  },
  {
    id: 'career-skill-development-s10',
    factorId: 'career-skill-development',
    title: 'Skill development',
    description: 'Experiment with one new approach or routine related to this factor.',
    impact: 78,
    category: 'ideal-gap',
  },
  {
    id: 'career-sense-of-purpose-s1',
    factorId: 'career-sense-of-purpose',
    title: 'Sense of purpose',
    description: 'Schedule a dedicated 30-minute block this week focused on this area.',
    impact: 66,
    category: 'ideal-gap',
  },
  {
    id: 'career-sense-of-purpose-s2',
    factorId: 'career-sense-of-purpose',
    title: 'Sense of purpose',
    description: 'Have a meaningful conversation with someone connected to this area.',
    impact: 74,
    category: 'ideal-gap',
  },
  {
    id: 'career-sense-of-purpose-s3',
    factorId: 'career-sense-of-purpose',
    title: 'Sense of purpose',
    description: 'Remove one friction point that makes this area harder than it should be.',
    impact: 80,
    category: 'ideal-gap',
  },
  {
    id: 'career-sense-of-purpose-s4',
    factorId: 'career-sense-of-purpose',
    title: 'Sense of purpose',
    description: 'Create a simple weekly habit that supports this factor.',
    impact: 90,
    category: 'ideal-gap',
  },
  {
    id: 'career-sense-of-purpose-s5',
    factorId: 'career-sense-of-purpose',
    title: 'Sense of purpose',
    description: 'Track your progress for the next 7 days.',
    impact: 67,
    category: 'ideal-gap',
  },
  {
    id: 'career-sense-of-purpose-s6',
    factorId: 'career-sense-of-purpose',
    title: 'Sense of purpose',
    description: 'Spend 20 minutes learning something new related to this area.',
    impact: 65,
    category: 'ideal-gap',
  },
  {
    id: 'career-sense-of-purpose-s7',
    factorId: 'career-sense-of-purpose',
    title: 'Sense of purpose',
    description: 'Plan a small activity this weekend that improves this factor.',
    impact: 73,
    category: 'ideal-gap',
  },
  {
    id: 'career-sense-of-purpose-s8',
    factorId: 'career-sense-of-purpose',
    title: 'Sense of purpose',
    description: 'Reflect for 10 minutes on what has helped or harmed this area recently.',
    impact: 60,
    category: 'ideal-gap',
  },
  {
    id: 'career-sense-of-purpose-s9',
    factorId: 'career-sense-of-purpose',
    title: 'Sense of purpose',
    description: 'Set a realistic improvement goal for the next month.',
    impact: 69,
    category: 'ideal-gap',
  },
  {
    id: 'career-sense-of-purpose-s10',
    factorId: 'career-sense-of-purpose',
    title: 'Sense of purpose',
    description: 'Experiment with one new approach or routine related to this factor.',
    impact: 87,
    category: 'ideal-gap',
  },
  {
    id: 'finances-income-stability-s1',
    factorId: 'finances-income-stability',
    title: 'Income stability',
    description: 'Schedule a dedicated 30-minute block this week focused on this area.',
    impact: 87,
    category: 'ideal-gap',
  },
  {
    id: 'finances-income-stability-s2',
    factorId: 'finances-income-stability',
    title: 'Income stability',
    description: 'Have a meaningful conversation with someone connected to this area.',
    impact: 67,
    category: 'ideal-gap',
  },
  {
    id: 'finances-income-stability-s3',
    factorId: 'finances-income-stability',
    title: 'Income stability',
    description: 'Remove one friction point that makes this area harder than it should be.',
    impact: 87,
    category: 'ideal-gap',
  },
  {
    id: 'finances-income-stability-s4',
    factorId: 'finances-income-stability',
    title: 'Income stability',
    description: 'Create a simple weekly habit that supports this factor.',
    impact: 69,
    category: 'ideal-gap',
  },
  {
    id: 'finances-income-stability-s5',
    factorId: 'finances-income-stability',
    title: 'Income stability',
    description: 'Track your progress for the next 7 days.',
    impact: 68,
    category: 'ideal-gap',
  },
  {
    id: 'finances-income-stability-s6',
    factorId: 'finances-income-stability',
    title: 'Income stability',
    description: 'Spend 20 minutes learning something new related to this area.',
    impact: 71,
    category: 'ideal-gap',
  },
  {
    id: 'finances-income-stability-s7',
    factorId: 'finances-income-stability',
    title: 'Income stability',
    description: 'Plan a small activity this weekend that improves this factor.',
    impact: 81,
    category: 'ideal-gap',
  },
  {
    id: 'finances-income-stability-s8',
    factorId: 'finances-income-stability',
    title: 'Income stability',
    description: 'Reflect for 10 minutes on what has helped or harmed this area recently.',
    impact: 89,
    category: 'ideal-gap',
  },
  {
    id: 'finances-income-stability-s9',
    factorId: 'finances-income-stability',
    title: 'Income stability',
    description: 'Set a realistic improvement goal for the next month.',
    impact: 84,
    category: 'ideal-gap',
  },
  {
    id: 'finances-income-stability-s10',
    factorId: 'finances-income-stability',
    title: 'Income stability',
    description: 'Experiment with one new approach or routine related to this factor.',
    impact: 66,
    category: 'ideal-gap',
  },
  {
    id: 'finances-savings-investments-s1',
    factorId: 'finances-savings-investments',
    title: 'Savings & investments',
    description: 'Schedule a dedicated 30-minute block this week focused on this area.',
    impact: 84,
    category: 'ideal-gap',
  },
  {
    id: 'finances-savings-investments-s2',
    factorId: 'finances-savings-investments',
    title: 'Savings & investments',
    description: 'Have a meaningful conversation with someone connected to this area.',
    impact: 68,
    category: 'ideal-gap',
  },
  {
    id: 'finances-savings-investments-s3',
    factorId: 'finances-savings-investments',
    title: 'Savings & investments',
    description: 'Remove one friction point that makes this area harder than it should be.',
    impact: 93,
    category: 'ideal-gap',
  },
  {
    id: 'finances-savings-investments-s4',
    factorId: 'finances-savings-investments',
    title: 'Savings & investments',
    description: 'Create a simple weekly habit that supports this factor.',
    impact: 88,
    category: 'ideal-gap',
  },
  {
    id: 'finances-savings-investments-s5',
    factorId: 'finances-savings-investments',
    title: 'Savings & investments',
    description: 'Track your progress for the next 7 days.',
    impact: 80,
    category: 'ideal-gap',
  },
  {
    id: 'finances-savings-investments-s6',
    factorId: 'finances-savings-investments',
    title: 'Savings & investments',
    description: 'Spend 20 minutes learning something new related to this area.',
    impact: 60,
    category: 'ideal-gap',
  },
  {
    id: 'finances-savings-investments-s7',
    factorId: 'finances-savings-investments',
    title: 'Savings & investments',
    description: 'Plan a small activity this weekend that improves this factor.',
    impact: 88,
    category: 'ideal-gap',
  },
  {
    id: 'finances-savings-investments-s8',
    factorId: 'finances-savings-investments',
    title: 'Savings & investments',
    description: 'Reflect for 10 minutes on what has helped or harmed this area recently.',
    impact: 69,
    category: 'ideal-gap',
  },
  {
    id: 'finances-savings-investments-s9',
    factorId: 'finances-savings-investments',
    title: 'Savings & investments',
    description: 'Set a realistic improvement goal for the next month.',
    impact: 89,
    category: 'ideal-gap',
  },
  {
    id: 'finances-savings-investments-s10',
    factorId: 'finances-savings-investments',
    title: 'Savings & investments',
    description: 'Experiment with one new approach or routine related to this factor.',
    impact: 69,
    category: 'ideal-gap',
  },
  {
    id: 'finances-spending-habits-s1',
    factorId: 'finances-spending-habits',
    title: 'Spending habits',
    description: 'Schedule a dedicated 30-minute block this week focused on this area.',
    impact: 76,
    category: 'ideal-gap',
  },
  {
    id: 'finances-spending-habits-s2',
    factorId: 'finances-spending-habits',
    title: 'Spending habits',
    description: 'Have a meaningful conversation with someone connected to this area.',
    impact: 68,
    category: 'ideal-gap',
  },
  {
    id: 'finances-spending-habits-s3',
    factorId: 'finances-spending-habits',
    title: 'Spending habits',
    description: 'Remove one friction point that makes this area harder than it should be.',
    impact: 67,
    category: 'ideal-gap',
  },
  {
    id: 'finances-spending-habits-s4',
    factorId: 'finances-spending-habits',
    title: 'Spending habits',
    description: 'Create a simple weekly habit that supports this factor.',
    impact: 68,
    category: 'ideal-gap',
  },
  {
    id: 'finances-spending-habits-s5',
    factorId: 'finances-spending-habits',
    title: 'Spending habits',
    description: 'Track your progress for the next 7 days.',
    impact: 89,
    category: 'ideal-gap',
  },
  {
    id: 'finances-spending-habits-s6',
    factorId: 'finances-spending-habits',
    title: 'Spending habits',
    description: 'Spend 20 minutes learning something new related to this area.',
    impact: 84,
    category: 'ideal-gap',
  },
  {
    id: 'finances-spending-habits-s7',
    factorId: 'finances-spending-habits',
    title: 'Spending habits',
    description: 'Plan a small activity this weekend that improves this factor.',
    impact: 66,
    category: 'ideal-gap',
  },
  {
    id: 'finances-spending-habits-s8',
    factorId: 'finances-spending-habits',
    title: 'Spending habits',
    description: 'Reflect for 10 minutes on what has helped or harmed this area recently.',
    impact: 95,
    category: 'ideal-gap',
  },
  {
    id: 'finances-spending-habits-s9',
    factorId: 'finances-spending-habits',
    title: 'Spending habits',
    description: 'Set a realistic improvement goal for the next month.',
    impact: 72,
    category: 'ideal-gap',
  },
  {
    id: 'finances-spending-habits-s10',
    factorId: 'finances-spending-habits',
    title: 'Spending habits',
    description: 'Experiment with one new approach or routine related to this factor.',
    impact: 60,
    category: 'ideal-gap',
  },
  {
    id: 'finances-financial-goals-clarity-s1',
    factorId: 'finances-financial-goals-clarity',
    title: 'Financial goals / clarity',
    description: 'Schedule a dedicated 30-minute block this week focused on this area.',
    impact: 68,
    category: 'ideal-gap',
  },
  {
    id: 'finances-financial-goals-clarity-s2',
    factorId: 'finances-financial-goals-clarity',
    title: 'Financial goals / clarity',
    description: 'Have a meaningful conversation with someone connected to this area.',
    impact: 85,
    category: 'ideal-gap',
  },
  {
    id: 'finances-financial-goals-clarity-s3',
    factorId: 'finances-financial-goals-clarity',
    title: 'Financial goals / clarity',
    description: 'Remove one friction point that makes this area harder than it should be.',
    impact: 66,
    category: 'ideal-gap',
  },
  {
    id: 'finances-financial-goals-clarity-s4',
    factorId: 'finances-financial-goals-clarity',
    title: 'Financial goals / clarity',
    description: 'Create a simple weekly habit that supports this factor.',
    impact: 90,
    category: 'ideal-gap',
  },
  {
    id: 'finances-financial-goals-clarity-s5',
    factorId: 'finances-financial-goals-clarity',
    title: 'Financial goals / clarity',
    description: 'Track your progress for the next 7 days.',
    impact: 70,
    category: 'ideal-gap',
  },
  {
    id: 'finances-financial-goals-clarity-s6',
    factorId: 'finances-financial-goals-clarity',
    title: 'Financial goals / clarity',
    description: 'Spend 20 minutes learning something new related to this area.',
    impact: 95,
    category: 'ideal-gap',
  },
  {
    id: 'finances-financial-goals-clarity-s7',
    factorId: 'finances-financial-goals-clarity',
    title: 'Financial goals / clarity',
    description: 'Plan a small activity this weekend that improves this factor.',
    impact: 78,
    category: 'ideal-gap',
  },
  {
    id: 'finances-financial-goals-clarity-s8',
    factorId: 'finances-financial-goals-clarity',
    title: 'Financial goals / clarity',
    description: 'Reflect for 10 minutes on what has helped or harmed this area recently.',
    impact: 62,
    category: 'ideal-gap',
  },
  {
    id: 'finances-financial-goals-clarity-s9',
    factorId: 'finances-financial-goals-clarity',
    title: 'Financial goals / clarity',
    description: 'Set a realistic improvement goal for the next month.',
    impact: 73,
    category: 'ideal-gap',
  },
  {
    id: 'finances-financial-goals-clarity-s10',
    factorId: 'finances-financial-goals-clarity',
    title: 'Financial goals / clarity',
    description: 'Experiment with one new approach or routine related to this factor.',
    impact: 70,
    category: 'ideal-gap',
  },
  {
    id: 'growth-learning-education-s1',
    factorId: 'growth-learning-education',
    title: 'Learning & education',
    description: 'Schedule a dedicated 30-minute block this week focused on this area.',
    impact: 70,
    category: 'ideal-gap',
  },
  {
    id: 'growth-learning-education-s2',
    factorId: 'growth-learning-education',
    title: 'Learning & education',
    description: 'Have a meaningful conversation with someone connected to this area.',
    impact: 80,
    category: 'ideal-gap',
  },
  {
    id: 'growth-learning-education-s3',
    factorId: 'growth-learning-education',
    title: 'Learning & education',
    description: 'Remove one friction point that makes this area harder than it should be.',
    impact: 91,
    category: 'ideal-gap',
  },
  {
    id: 'growth-learning-education-s4',
    factorId: 'growth-learning-education',
    title: 'Learning & education',
    description: 'Create a simple weekly habit that supports this factor.',
    impact: 80,
    category: 'ideal-gap',
  },
  {
    id: 'growth-learning-education-s5',
    factorId: 'growth-learning-education',
    title: 'Learning & education',
    description: 'Track your progress for the next 7 days.',
    impact: 65,
    category: 'ideal-gap',
  },
  {
    id: 'growth-learning-education-s6',
    factorId: 'growth-learning-education',
    title: 'Learning & education',
    description: 'Spend 20 minutes learning something new related to this area.',
    impact: 65,
    category: 'ideal-gap',
  },
  {
    id: 'growth-learning-education-s7',
    factorId: 'growth-learning-education',
    title: 'Learning & education',
    description: 'Plan a small activity this weekend that improves this factor.',
    impact: 81,
    category: 'ideal-gap',
  },
  {
    id: 'growth-learning-education-s8',
    factorId: 'growth-learning-education',
    title: 'Learning & education',
    description: 'Reflect for 10 minutes on what has helped or harmed this area recently.',
    impact: 84,
    category: 'ideal-gap',
  },
  {
    id: 'growth-learning-education-s9',
    factorId: 'growth-learning-education',
    title: 'Learning & education',
    description: 'Set a realistic improvement goal for the next month.',
    impact: 79,
    category: 'ideal-gap',
  },
  {
    id: 'growth-learning-education-s10',
    factorId: 'growth-learning-education',
    title: 'Learning & education',
    description: 'Experiment with one new approach or routine related to this factor.',
    impact: 81,
    category: 'ideal-gap',
  },
  {
    id: 'growth-self-reflection-s1',
    factorId: 'growth-self-reflection',
    title: 'Self-reflection',
    description: 'Schedule a dedicated 30-minute block this week focused on this area.',
    impact: 66,
    category: 'ideal-gap',
  },
  {
    id: 'growth-self-reflection-s2',
    factorId: 'growth-self-reflection',
    title: 'Self-reflection',
    description: 'Have a meaningful conversation with someone connected to this area.',
    impact: 88,
    category: 'ideal-gap',
  },
  {
    id: 'growth-self-reflection-s3',
    factorId: 'growth-self-reflection',
    title: 'Self-reflection',
    description: 'Remove one friction point that makes this area harder than it should be.',
    impact: 81,
    category: 'ideal-gap',
  },
  {
    id: 'growth-self-reflection-s4',
    factorId: 'growth-self-reflection',
    title: 'Self-reflection',
    description: 'Create a simple weekly habit that supports this factor.',
    impact: 83,
    category: 'ideal-gap',
  },
  {
    id: 'growth-self-reflection-s5',
    factorId: 'growth-self-reflection',
    title: 'Self-reflection',
    description: 'Track your progress for the next 7 days.',
    impact: 78,
    category: 'ideal-gap',
  },
  {
    id: 'growth-self-reflection-s6',
    factorId: 'growth-self-reflection',
    title: 'Self-reflection',
    description: 'Spend 20 minutes learning something new related to this area.',
    impact: 85,
    category: 'ideal-gap',
  },
  {
    id: 'growth-self-reflection-s7',
    factorId: 'growth-self-reflection',
    title: 'Self-reflection',
    description: 'Plan a small activity this weekend that improves this factor.',
    impact: 94,
    category: 'ideal-gap',
  },
  {
    id: 'growth-self-reflection-s8',
    factorId: 'growth-self-reflection',
    title: 'Self-reflection',
    description: 'Reflect for 10 minutes on what has helped or harmed this area recently.',
    impact: 62,
    category: 'ideal-gap',
  },
  {
    id: 'growth-self-reflection-s9',
    factorId: 'growth-self-reflection',
    title: 'Self-reflection',
    description: 'Set a realistic improvement goal for the next month.',
    impact: 60,
    category: 'ideal-gap',
  },
  {
    id: 'growth-self-reflection-s10',
    factorId: 'growth-self-reflection',
    title: 'Self-reflection',
    description: 'Experiment with one new approach or routine related to this factor.',
    impact: 72,
    category: 'ideal-gap',
  },
  {
    id: 'growth-resilience-stress-coping-s1',
    factorId: 'growth-resilience-stress-coping',
    title: 'Resilience / stress coping',
    description: 'Schedule a dedicated 30-minute block this week focused on this area.',
    impact: 60,
    category: 'ideal-gap',
  },
  {
    id: 'growth-resilience-stress-coping-s2',
    factorId: 'growth-resilience-stress-coping',
    title: 'Resilience / stress coping',
    description: 'Have a meaningful conversation with someone connected to this area.',
    impact: 69,
    category: 'ideal-gap',
  },
  {
    id: 'growth-resilience-stress-coping-s3',
    factorId: 'growth-resilience-stress-coping',
    title: 'Resilience / stress coping',
    description: 'Remove one friction point that makes this area harder than it should be.',
    impact: 65,
    category: 'ideal-gap',
  },
  {
    id: 'growth-resilience-stress-coping-s4',
    factorId: 'growth-resilience-stress-coping',
    title: 'Resilience / stress coping',
    description: 'Create a simple weekly habit that supports this factor.',
    impact: 83,
    category: 'ideal-gap',
  },
  {
    id: 'growth-resilience-stress-coping-s5',
    factorId: 'growth-resilience-stress-coping',
    title: 'Resilience / stress coping',
    description: 'Track your progress for the next 7 days.',
    impact: 75,
    category: 'ideal-gap',
  },
  {
    id: 'growth-resilience-stress-coping-s6',
    factorId: 'growth-resilience-stress-coping',
    title: 'Resilience / stress coping',
    description: 'Spend 20 minutes learning something new related to this area.',
    impact: 61,
    category: 'ideal-gap',
  },
  {
    id: 'growth-resilience-stress-coping-s7',
    factorId: 'growth-resilience-stress-coping',
    title: 'Resilience / stress coping',
    description: 'Plan a small activity this weekend that improves this factor.',
    impact: 73,
    category: 'ideal-gap',
  },
  {
    id: 'growth-resilience-stress-coping-s8',
    factorId: 'growth-resilience-stress-coping',
    title: 'Resilience / stress coping',
    description: 'Reflect for 10 minutes on what has helped or harmed this area recently.',
    impact: 94,
    category: 'ideal-gap',
  },
  {
    id: 'growth-resilience-stress-coping-s9',
    factorId: 'growth-resilience-stress-coping',
    title: 'Resilience / stress coping',
    description: 'Set a realistic improvement goal for the next month.',
    impact: 72,
    category: 'ideal-gap',
  },
  {
    id: 'growth-resilience-stress-coping-s10',
    factorId: 'growth-resilience-stress-coping',
    title: 'Resilience / stress coping',
    description: 'Experiment with one new approach or routine related to this factor.',
    impact: 62,
    category: 'ideal-gap',
  },
  {
    id: 'growth-trying-new-things-s1',
    factorId: 'growth-trying-new-things',
    title: 'Trying new things',
    description: 'Schedule a dedicated 30-minute block this week focused on this area.',
    impact: 60,
    category: 'ideal-gap',
  },
  {
    id: 'growth-trying-new-things-s2',
    factorId: 'growth-trying-new-things',
    title: 'Trying new things',
    description: 'Have a meaningful conversation with someone connected to this area.',
    impact: 71,
    category: 'ideal-gap',
  },
  {
    id: 'growth-trying-new-things-s3',
    factorId: 'growth-trying-new-things',
    title: 'Trying new things',
    description: 'Remove one friction point that makes this area harder than it should be.',
    impact: 62,
    category: 'ideal-gap',
  },
  {
    id: 'growth-trying-new-things-s4',
    factorId: 'growth-trying-new-things',
    title: 'Trying new things',
    description: 'Create a simple weekly habit that supports this factor.',
    impact: 76,
    category: 'ideal-gap',
  },
  {
    id: 'growth-trying-new-things-s5',
    factorId: 'growth-trying-new-things',
    title: 'Trying new things',
    description: 'Track your progress for the next 7 days.',
    impact: 75,
    category: 'ideal-gap',
  },
  {
    id: 'growth-trying-new-things-s6',
    factorId: 'growth-trying-new-things',
    title: 'Trying new things',
    description: 'Spend 20 minutes learning something new related to this area.',
    impact: 66,
    category: 'ideal-gap',
  },
  {
    id: 'growth-trying-new-things-s7',
    factorId: 'growth-trying-new-things',
    title: 'Trying new things',
    description: 'Plan a small activity this weekend that improves this factor.',
    impact: 65,
    category: 'ideal-gap',
  },
  {
    id: 'growth-trying-new-things-s8',
    factorId: 'growth-trying-new-things',
    title: 'Trying new things',
    description: 'Reflect for 10 minutes on what has helped or harmed this area recently.',
    impact: 88,
    category: 'ideal-gap',
  },
  {
    id: 'growth-trying-new-things-s9',
    factorId: 'growth-trying-new-things',
    title: 'Trying new things',
    description: 'Set a realistic improvement goal for the next month.',
    impact: 71,
    category: 'ideal-gap',
  },
  {
    id: 'growth-trying-new-things-s10',
    factorId: 'growth-trying-new-things',
    title: 'Trying new things',
    description: 'Experiment with one new approach or routine related to this factor.',
    impact: 67,
    category: 'ideal-gap',
  },
  {
    id: 'leisure-hobbies-s1',
    factorId: 'leisure-hobbies',
    title: 'Hobbies',
    description: 'Schedule a dedicated 30-minute block this week focused on this area.',
    impact: 90,
    category: 'ideal-gap',
  },
  {
    id: 'leisure-hobbies-s2',
    factorId: 'leisure-hobbies',
    title: 'Hobbies',
    description: 'Have a meaningful conversation with someone connected to this area.',
    impact: 68,
    category: 'ideal-gap',
  },
  {
    id: 'leisure-hobbies-s3',
    factorId: 'leisure-hobbies',
    title: 'Hobbies',
    description: 'Remove one friction point that makes this area harder than it should be.',
    impact: 61,
    category: 'ideal-gap',
  },
  {
    id: 'leisure-hobbies-s4',
    factorId: 'leisure-hobbies',
    title: 'Hobbies',
    description: 'Create a simple weekly habit that supports this factor.',
    impact: 68,
    category: 'ideal-gap',
  },
  {
    id: 'leisure-hobbies-s5',
    factorId: 'leisure-hobbies',
    title: 'Hobbies',
    description: 'Track your progress for the next 7 days.',
    impact: 90,
    category: 'ideal-gap',
  },
  {
    id: 'leisure-hobbies-s6',
    factorId: 'leisure-hobbies',
    title: 'Hobbies',
    description: 'Spend 20 minutes learning something new related to this area.',
    impact: 72,
    category: 'ideal-gap',
  },
  {
    id: 'leisure-hobbies-s7',
    factorId: 'leisure-hobbies',
    title: 'Hobbies',
    description: 'Plan a small activity this weekend that improves this factor.',
    impact: 91,
    category: 'ideal-gap',
  },
  {
    id: 'leisure-hobbies-s8',
    factorId: 'leisure-hobbies',
    title: 'Hobbies',
    description: 'Reflect for 10 minutes on what has helped or harmed this area recently.',
    impact: 81,
    category: 'ideal-gap',
  },
  {
    id: 'leisure-hobbies-s9',
    factorId: 'leisure-hobbies',
    title: 'Hobbies',
    description: 'Set a realistic improvement goal for the next month.',
    impact: 72,
    category: 'ideal-gap',
  },
  {
    id: 'leisure-hobbies-s10',
    factorId: 'leisure-hobbies',
    title: 'Hobbies',
    description: 'Experiment with one new approach or routine related to this factor.',
    impact: 80,
    category: 'ideal-gap',
  },
  {
    id: 'leisure-entertainment-s1',
    factorId: 'leisure-entertainment',
    title: 'Entertainment',
    description: 'Schedule a dedicated 30-minute block this week focused on this area.',
    impact: 60,
    category: 'ideal-gap',
  },
  {
    id: 'leisure-entertainment-s2',
    factorId: 'leisure-entertainment',
    title: 'Entertainment',
    description: 'Have a meaningful conversation with someone connected to this area.',
    impact: 74,
    category: 'ideal-gap',
  },
  {
    id: 'leisure-entertainment-s3',
    factorId: 'leisure-entertainment',
    title: 'Entertainment',
    description: 'Remove one friction point that makes this area harder than it should be.',
    impact: 82,
    category: 'ideal-gap',
  },
  {
    id: 'leisure-entertainment-s4',
    factorId: 'leisure-entertainment',
    title: 'Entertainment',
    description: 'Create a simple weekly habit that supports this factor.',
    impact: 77,
    category: 'ideal-gap',
  },
  {
    id: 'leisure-entertainment-s5',
    factorId: 'leisure-entertainment',
    title: 'Entertainment',
    description: 'Track your progress for the next 7 days.',
    impact: 63,
    category: 'ideal-gap',
  },
  {
    id: 'leisure-entertainment-s6',
    factorId: 'leisure-entertainment',
    title: 'Entertainment',
    description: 'Spend 20 minutes learning something new related to this area.',
    impact: 81,
    category: 'ideal-gap',
  },
  {
    id: 'leisure-entertainment-s7',
    factorId: 'leisure-entertainment',
    title: 'Entertainment',
    description: 'Plan a small activity this weekend that improves this factor.',
    impact: 77,
    category: 'ideal-gap',
  },
  {
    id: 'leisure-entertainment-s8',
    factorId: 'leisure-entertainment',
    title: 'Entertainment',
    description: 'Reflect for 10 minutes on what has helped or harmed this area recently.',
    impact: 83,
    category: 'ideal-gap',
  },
  {
    id: 'leisure-entertainment-s9',
    factorId: 'leisure-entertainment',
    title: 'Entertainment',
    description: 'Set a realistic improvement goal for the next month.',
    impact: 69,
    category: 'ideal-gap',
  },
  {
    id: 'leisure-entertainment-s10',
    factorId: 'leisure-entertainment',
    title: 'Entertainment',
    description: 'Experiment with one new approach or routine related to this factor.',
    impact: 69,
    category: 'ideal-gap',
  },
  {
    id: 'leisure-social-outings-s1',
    factorId: 'leisure-social-outings',
    title: 'Social outings',
    description: 'Schedule a dedicated 30-minute block this week focused on this area.',
    impact: 63,
    category: 'ideal-gap',
  },
  {
    id: 'leisure-social-outings-s2',
    factorId: 'leisure-social-outings',
    title: 'Social outings',
    description: 'Have a meaningful conversation with someone connected to this area.',
    impact: 77,
    category: 'ideal-gap',
  },
  {
    id: 'leisure-social-outings-s3',
    factorId: 'leisure-social-outings',
    title: 'Social outings',
    description: 'Remove one friction point that makes this area harder than it should be.',
    impact: 80,
    category: 'ideal-gap',
  },
  {
    id: 'leisure-social-outings-s4',
    factorId: 'leisure-social-outings',
    title: 'Social outings',
    description: 'Create a simple weekly habit that supports this factor.',
    impact: 79,
    category: 'ideal-gap',
  },
  {
    id: 'leisure-social-outings-s5',
    factorId: 'leisure-social-outings',
    title: 'Social outings',
    description: 'Track your progress for the next 7 days.',
    impact: 68,
    category: 'ideal-gap',
  },
  {
    id: 'leisure-social-outings-s6',
    factorId: 'leisure-social-outings',
    title: 'Social outings',
    description: 'Spend 20 minutes learning something new related to this area.',
    impact: 95,
    category: 'ideal-gap',
  },
  {
    id: 'leisure-social-outings-s7',
    factorId: 'leisure-social-outings',
    title: 'Social outings',
    description: 'Plan a small activity this weekend that improves this factor.',
    impact: 67,
    category: 'ideal-gap',
  },
  {
    id: 'leisure-social-outings-s8',
    factorId: 'leisure-social-outings',
    title: 'Social outings',
    description: 'Reflect for 10 minutes on what has helped or harmed this area recently.',
    impact: 87,
    category: 'ideal-gap',
  },
  {
    id: 'leisure-social-outings-s9',
    factorId: 'leisure-social-outings',
    title: 'Social outings',
    description: 'Set a realistic improvement goal for the next month.',
    impact: 81,
    category: 'ideal-gap',
  },
  {
    id: 'leisure-social-outings-s10',
    factorId: 'leisure-social-outings',
    title: 'Social outings',
    description: 'Experiment with one new approach or routine related to this factor.',
    impact: 63,
    category: 'ideal-gap',
  },
  {
    id: 'leisure-travel-exploration-s1',
    factorId: 'leisure-travel-exploration',
    title: 'Travel / exploration',
    description: 'Schedule a dedicated 30-minute block this week focused on this area.',
    impact: 70,
    category: 'ideal-gap',
  },
  {
    id: 'leisure-travel-exploration-s2',
    factorId: 'leisure-travel-exploration',
    title: 'Travel / exploration',
    description: 'Have a meaningful conversation with someone connected to this area.',
    impact: 93,
    category: 'ideal-gap',
  },
  {
    id: 'leisure-travel-exploration-s3',
    factorId: 'leisure-travel-exploration',
    title: 'Travel / exploration',
    description: 'Remove one friction point that makes this area harder than it should be.',
    impact: 69,
    category: 'ideal-gap',
  },
  {
    id: 'leisure-travel-exploration-s4',
    factorId: 'leisure-travel-exploration',
    title: 'Travel / exploration',
    description: 'Create a simple weekly habit that supports this factor.',
    impact: 74,
    category: 'ideal-gap',
  },
  {
    id: 'leisure-travel-exploration-s5',
    factorId: 'leisure-travel-exploration',
    title: 'Travel / exploration',
    description: 'Track your progress for the next 7 days.',
    impact: 93,
    category: 'ideal-gap',
  },
  {
    id: 'leisure-travel-exploration-s6',
    factorId: 'leisure-travel-exploration',
    title: 'Travel / exploration',
    description: 'Spend 20 minutes learning something new related to this area.',
    impact: 64,
    category: 'ideal-gap',
  },
  {
    id: 'leisure-travel-exploration-s7',
    factorId: 'leisure-travel-exploration',
    title: 'Travel / exploration',
    description: 'Plan a small activity this weekend that improves this factor.',
    impact: 94,
    category: 'ideal-gap',
  },
  {
    id: 'leisure-travel-exploration-s8',
    factorId: 'leisure-travel-exploration',
    title: 'Travel / exploration',
    description: 'Reflect for 10 minutes on what has helped or harmed this area recently.',
    impact: 66,
    category: 'ideal-gap',
  },
  {
    id: 'leisure-travel-exploration-s9',
    factorId: 'leisure-travel-exploration',
    title: 'Travel / exploration',
    description: 'Set a realistic improvement goal for the next month.',
    impact: 89,
    category: 'ideal-gap',
  },
  {
    id: 'leisure-travel-exploration-s10',
    factorId: 'leisure-travel-exploration',
    title: 'Travel / exploration',
    description: 'Experiment with one new approach or routine related to this factor.',
    impact: 79,
    category: 'ideal-gap',
  },
  {
    id: 'environment-home-comfort-s1',
    factorId: 'environment-home-comfort',
    title: 'Home comfort',
    description: 'Schedule a dedicated 30-minute block this week focused on this area.',
    impact: 93,
    category: 'ideal-gap',
  },
  {
    id: 'environment-home-comfort-s2',
    factorId: 'environment-home-comfort',
    title: 'Home comfort',
    description: 'Have a meaningful conversation with someone connected to this area.',
    impact: 76,
    category: 'ideal-gap',
  },
  {
    id: 'environment-home-comfort-s3',
    factorId: 'environment-home-comfort',
    title: 'Home comfort',
    description: 'Remove one friction point that makes this area harder than it should be.',
    impact: 83,
    category: 'ideal-gap',
  },
  {
    id: 'environment-home-comfort-s4',
    factorId: 'environment-home-comfort',
    title: 'Home comfort',
    description: 'Create a simple weekly habit that supports this factor.',
    impact: 61,
    category: 'ideal-gap',
  },
  {
    id: 'environment-home-comfort-s5',
    factorId: 'environment-home-comfort',
    title: 'Home comfort',
    description: 'Track your progress for the next 7 days.',
    impact: 84,
    category: 'ideal-gap',
  },
  {
    id: 'environment-home-comfort-s6',
    factorId: 'environment-home-comfort',
    title: 'Home comfort',
    description: 'Spend 20 minutes learning something new related to this area.',
    impact: 61,
    category: 'ideal-gap',
  },
  {
    id: 'environment-home-comfort-s7',
    factorId: 'environment-home-comfort',
    title: 'Home comfort',
    description: 'Plan a small activity this weekend that improves this factor.',
    impact: 93,
    category: 'ideal-gap',
  },
  {
    id: 'environment-home-comfort-s8',
    factorId: 'environment-home-comfort',
    title: 'Home comfort',
    description: 'Reflect for 10 minutes on what has helped or harmed this area recently.',
    impact: 93,
    category: 'ideal-gap',
  },
  {
    id: 'environment-home-comfort-s9',
    factorId: 'environment-home-comfort',
    title: 'Home comfort',
    description: 'Set a realistic improvement goal for the next month.',
    impact: 66,
    category: 'ideal-gap',
  },
  {
    id: 'environment-home-comfort-s10',
    factorId: 'environment-home-comfort',
    title: 'Home comfort',
    description: 'Experiment with one new approach or routine related to this factor.',
    impact: 75,
    category: 'ideal-gap',
  },
  {
    id: 'environment-workspace-quality-s1',
    factorId: 'environment-workspace-quality',
    title: 'Workspace quality',
    description: 'Schedule a dedicated 30-minute block this week focused on this area.',
    impact: 92,
    category: 'ideal-gap',
  },
  {
    id: 'environment-workspace-quality-s2',
    factorId: 'environment-workspace-quality',
    title: 'Workspace quality',
    description: 'Have a meaningful conversation with someone connected to this area.',
    impact: 94,
    category: 'ideal-gap',
  },
  {
    id: 'environment-workspace-quality-s3',
    factorId: 'environment-workspace-quality',
    title: 'Workspace quality',
    description: 'Remove one friction point that makes this area harder than it should be.',
    impact: 85,
    category: 'ideal-gap',
  },
  {
    id: 'environment-workspace-quality-s4',
    factorId: 'environment-workspace-quality',
    title: 'Workspace quality',
    description: 'Create a simple weekly habit that supports this factor.',
    impact: 64,
    category: 'ideal-gap',
  },
  {
    id: 'environment-workspace-quality-s5',
    factorId: 'environment-workspace-quality',
    title: 'Workspace quality',
    description: 'Track your progress for the next 7 days.',
    impact: 67,
    category: 'ideal-gap',
  },
  {
    id: 'environment-workspace-quality-s6',
    factorId: 'environment-workspace-quality',
    title: 'Workspace quality',
    description: 'Spend 20 minutes learning something new related to this area.',
    impact: 91,
    category: 'ideal-gap',
  },
  {
    id: 'environment-workspace-quality-s7',
    factorId: 'environment-workspace-quality',
    title: 'Workspace quality',
    description: 'Plan a small activity this weekend that improves this factor.',
    impact: 73,
    category: 'ideal-gap',
  },
  {
    id: 'environment-workspace-quality-s8',
    factorId: 'environment-workspace-quality',
    title: 'Workspace quality',
    description: 'Reflect for 10 minutes on what has helped or harmed this area recently.',
    impact: 71,
    category: 'ideal-gap',
  },
  {
    id: 'environment-workspace-quality-s9',
    factorId: 'environment-workspace-quality',
    title: 'Workspace quality',
    description: 'Set a realistic improvement goal for the next month.',
    impact: 78,
    category: 'ideal-gap',
  },
  {
    id: 'environment-workspace-quality-s10',
    factorId: 'environment-workspace-quality',
    title: 'Workspace quality',
    description: 'Experiment with one new approach or routine related to this factor.',
    impact: 80,
    category: 'ideal-gap',
  },
  {
    id: 'environment-connection-to-nature-s1',
    factorId: 'environment-connection-to-nature',
    title: 'Connection to nature',
    description: 'Schedule a dedicated 30-minute block this week focused on this area.',
    impact: 82,
    category: 'ideal-gap',
  },
  {
    id: 'environment-connection-to-nature-s2',
    factorId: 'environment-connection-to-nature',
    title: 'Connection to nature',
    description: 'Have a meaningful conversation with someone connected to this area.',
    impact: 80,
    category: 'ideal-gap',
  },
  {
    id: 'environment-connection-to-nature-s3',
    factorId: 'environment-connection-to-nature',
    title: 'Connection to nature',
    description: 'Remove one friction point that makes this area harder than it should be.',
    impact: 64,
    category: 'ideal-gap',
  },
  {
    id: 'environment-connection-to-nature-s4',
    factorId: 'environment-connection-to-nature',
    title: 'Connection to nature',
    description: 'Create a simple weekly habit that supports this factor.',
    impact: 85,
    category: 'ideal-gap',
  },
  {
    id: 'environment-connection-to-nature-s5',
    factorId: 'environment-connection-to-nature',
    title: 'Connection to nature',
    description: 'Track your progress for the next 7 days.',
    impact: 94,
    category: 'ideal-gap',
  },
  {
    id: 'environment-connection-to-nature-s6',
    factorId: 'environment-connection-to-nature',
    title: 'Connection to nature',
    description: 'Spend 20 minutes learning something new related to this area.',
    impact: 83,
    category: 'ideal-gap',
  },
  {
    id: 'environment-connection-to-nature-s7',
    factorId: 'environment-connection-to-nature',
    title: 'Connection to nature',
    description: 'Plan a small activity this weekend that improves this factor.',
    impact: 64,
    category: 'ideal-gap',
  },
  {
    id: 'environment-connection-to-nature-s8',
    factorId: 'environment-connection-to-nature',
    title: 'Connection to nature',
    description: 'Reflect for 10 minutes on what has helped or harmed this area recently.',
    impact: 75,
    category: 'ideal-gap',
  },
  {
    id: 'environment-connection-to-nature-s9',
    factorId: 'environment-connection-to-nature',
    title: 'Connection to nature',
    description: 'Set a realistic improvement goal for the next month.',
    impact: 77,
    category: 'ideal-gap',
  },
  {
    id: 'environment-connection-to-nature-s10',
    factorId: 'environment-connection-to-nature',
    title: 'Connection to nature',
    description: 'Experiment with one new approach or routine related to this factor.',
    impact: 89,
    category: 'ideal-gap',
  },
  {
    id: 'environment-organization-clutter-s1',
    factorId: 'environment-organization-clutter',
    title: 'Organization / clutter',
    description: 'Schedule a dedicated 30-minute block this week focused on this area.',
    impact: 79,
    category: 'ideal-gap',
  },
  {
    id: 'environment-organization-clutter-s2',
    factorId: 'environment-organization-clutter',
    title: 'Organization / clutter',
    description: 'Have a meaningful conversation with someone connected to this area.',
    impact: 60,
    category: 'ideal-gap',
  },
  {
    id: 'environment-organization-clutter-s3',
    factorId: 'environment-organization-clutter',
    title: 'Organization / clutter',
    description: 'Remove one friction point that makes this area harder than it should be.',
    impact: 72,
    category: 'ideal-gap',
  },
  {
    id: 'environment-organization-clutter-s4',
    factorId: 'environment-organization-clutter',
    title: 'Organization / clutter',
    description: 'Create a simple weekly habit that supports this factor.',
    impact: 66,
    category: 'ideal-gap',
  },
  {
    id: 'environment-organization-clutter-s5',
    factorId: 'environment-organization-clutter',
    title: 'Organization / clutter',
    description: 'Track your progress for the next 7 days.',
    impact: 94,
    category: 'ideal-gap',
  },
  {
    id: 'environment-organization-clutter-s6',
    factorId: 'environment-organization-clutter',
    title: 'Organization / clutter',
    description: 'Spend 20 minutes learning something new related to this area.',
    impact: 80,
    category: 'ideal-gap',
  },
  {
    id: 'environment-organization-clutter-s7',
    factorId: 'environment-organization-clutter',
    title: 'Organization / clutter',
    description: 'Plan a small activity this weekend that improves this factor.',
    impact: 86,
    category: 'ideal-gap',
  },
  {
    id: 'environment-organization-clutter-s8',
    factorId: 'environment-organization-clutter',
    title: 'Organization / clutter',
    description: 'Reflect for 10 minutes on what has helped or harmed this area recently.',
    impact: 89,
    category: 'ideal-gap',
  },
  {
    id: 'environment-organization-clutter-s9',
    factorId: 'environment-organization-clutter',
    title: 'Organization / clutter',
    description: 'Set a realistic improvement goal for the next month.',
    impact: 89,
    category: 'ideal-gap',
  },
  {
    id: 'environment-organization-clutter-s10',
    factorId: 'environment-organization-clutter',
    title: 'Organization / clutter',
    description: 'Experiment with one new approach or routine related to this factor.',
    impact: 79,
    category: 'ideal-gap',
  },
  {
    id: 'creativity-art-music-engagement-s1',
    factorId: 'creativity-art-music-engagement',
    title: 'Art/music engagement',
    description: 'Schedule a dedicated 30-minute block this week focused on this area.',
    impact: 95,
    category: 'ideal-gap',
  },
  {
    id: 'creativity-art-music-engagement-s2',
    factorId: 'creativity-art-music-engagement',
    title: 'Art/music engagement',
    description: 'Have a meaningful conversation with someone connected to this area.',
    impact: 66,
    category: 'ideal-gap',
  },
  {
    id: 'creativity-art-music-engagement-s3',
    factorId: 'creativity-art-music-engagement',
    title: 'Art/music engagement',
    description: 'Remove one friction point that makes this area harder than it should be.',
    impact: 85,
    category: 'ideal-gap',
  },
  {
    id: 'creativity-art-music-engagement-s4',
    factorId: 'creativity-art-music-engagement',
    title: 'Art/music engagement',
    description: 'Create a simple weekly habit that supports this factor.',
    impact: 79,
    category: 'ideal-gap',
  },
  {
    id: 'creativity-art-music-engagement-s5',
    factorId: 'creativity-art-music-engagement',
    title: 'Art/music engagement',
    description: 'Track your progress for the next 7 days.',
    impact: 77,
    category: 'ideal-gap',
  },
  {
    id: 'creativity-art-music-engagement-s6',
    factorId: 'creativity-art-music-engagement',
    title: 'Art/music engagement',
    description: 'Spend 20 minutes learning something new related to this area.',
    impact: 69,
    category: 'ideal-gap',
  },
  {
    id: 'creativity-art-music-engagement-s7',
    factorId: 'creativity-art-music-engagement',
    title: 'Art/music engagement',
    description: 'Plan a small activity this weekend that improves this factor.',
    impact: 94,
    category: 'ideal-gap',
  },
  {
    id: 'creativity-art-music-engagement-s8',
    factorId: 'creativity-art-music-engagement',
    title: 'Art/music engagement',
    description: 'Reflect for 10 minutes on what has helped or harmed this area recently.',
    impact: 82,
    category: 'ideal-gap',
  },
  {
    id: 'creativity-art-music-engagement-s9',
    factorId: 'creativity-art-music-engagement',
    title: 'Art/music engagement',
    description: 'Set a realistic improvement goal for the next month.',
    impact: 74,
    category: 'ideal-gap',
  },
  {
    id: 'creativity-art-music-engagement-s10',
    factorId: 'creativity-art-music-engagement',
    title: 'Art/music engagement',
    description: 'Experiment with one new approach or routine related to this factor.',
    impact: 80,
    category: 'ideal-gap',
  },
  {
    id: 'creativity-creating-writing-making-s1',
    factorId: 'creativity-creating-writing-making',
    title: 'Creating (writing/making/etc.)',
    description: 'Schedule a dedicated 30-minute block this week focused on this area.',
    impact: 92,
    category: 'ideal-gap',
  },
  {
    id: 'creativity-creating-writing-making-s2',
    factorId: 'creativity-creating-writing-making',
    title: 'Creating (writing/making/etc.)',
    description: 'Have a meaningful conversation with someone connected to this area.',
    impact: 79,
    category: 'ideal-gap',
  },
  {
    id: 'creativity-creating-writing-making-s3',
    factorId: 'creativity-creating-writing-making',
    title: 'Creating (writing/making/etc.)',
    description: 'Remove one friction point that makes this area harder than it should be.',
    impact: 72,
    category: 'ideal-gap',
  },
  {
    id: 'creativity-creating-writing-making-s4',
    factorId: 'creativity-creating-writing-making',
    title: 'Creating (writing/making/etc.)',
    description: 'Create a simple weekly habit that supports this factor.',
    impact: 90,
    category: 'ideal-gap',
  },
  {
    id: 'creativity-creating-writing-making-s5',
    factorId: 'creativity-creating-writing-making',
    title: 'Creating (writing/making/etc.)',
    description: 'Track your progress for the next 7 days.',
    impact: 83,
    category: 'ideal-gap',
  },
  {
    id: 'creativity-creating-writing-making-s6',
    factorId: 'creativity-creating-writing-making',
    title: 'Creating (writing/making/etc.)',
    description: 'Spend 20 minutes learning something new related to this area.',
    impact: 74,
    category: 'ideal-gap',
  },
  {
    id: 'creativity-creating-writing-making-s7',
    factorId: 'creativity-creating-writing-making',
    title: 'Creating (writing/making/etc.)',
    description: 'Plan a small activity this weekend that improves this factor.',
    impact: 80,
    category: 'ideal-gap',
  },
  {
    id: 'creativity-creating-writing-making-s8',
    factorId: 'creativity-creating-writing-making',
    title: 'Creating (writing/making/etc.)',
    description: 'Reflect for 10 minutes on what has helped or harmed this area recently.',
    impact: 80,
    category: 'ideal-gap',
  },
  {
    id: 'creativity-creating-writing-making-s9',
    factorId: 'creativity-creating-writing-making',
    title: 'Creating (writing/making/etc.)',
    description: 'Set a realistic improvement goal for the next month.',
    impact: 95,
    category: 'ideal-gap',
  },
  {
    id: 'creativity-creating-writing-making-s10',
    factorId: 'creativity-creating-writing-making',
    title: 'Creating (writing/making/etc.)',
    description: 'Experiment with one new approach or routine related to this factor.',
    impact: 84,
    category: 'ideal-gap',
  },
  {
    id: 'creativity-personal-style-self-expression-s1',
    factorId: 'creativity-personal-style-self-expression',
    title: 'Personal style / self-expression',
    description: 'Schedule a dedicated 30-minute block this week focused on this area.',
    impact: 71,
    category: 'ideal-gap',
  },
  {
    id: 'creativity-personal-style-self-expression-s2',
    factorId: 'creativity-personal-style-self-expression',
    title: 'Personal style / self-expression',
    description: 'Have a meaningful conversation with someone connected to this area.',
    impact: 72,
    category: 'ideal-gap',
  },
  {
    id: 'creativity-personal-style-self-expression-s3',
    factorId: 'creativity-personal-style-self-expression',
    title: 'Personal style / self-expression',
    description: 'Remove one friction point that makes this area harder than it should be.',
    impact: 92,
    category: 'ideal-gap',
  },
  {
    id: 'creativity-personal-style-self-expression-s4',
    factorId: 'creativity-personal-style-self-expression',
    title: 'Personal style / self-expression',
    description: 'Create a simple weekly habit that supports this factor.',
    impact: 66,
    category: 'ideal-gap',
  },
  {
    id: 'creativity-personal-style-self-expression-s5',
    factorId: 'creativity-personal-style-self-expression',
    title: 'Personal style / self-expression',
    description: 'Track your progress for the next 7 days.',
    impact: 75,
    category: 'ideal-gap',
  },
  {
    id: 'creativity-personal-style-self-expression-s6',
    factorId: 'creativity-personal-style-self-expression',
    title: 'Personal style / self-expression',
    description: 'Spend 20 minutes learning something new related to this area.',
    impact: 61,
    category: 'ideal-gap',
  },
  {
    id: 'creativity-personal-style-self-expression-s7',
    factorId: 'creativity-personal-style-self-expression',
    title: 'Personal style / self-expression',
    description: 'Plan a small activity this weekend that improves this factor.',
    impact: 62,
    category: 'ideal-gap',
  },
  {
    id: 'creativity-personal-style-self-expression-s8',
    factorId: 'creativity-personal-style-self-expression',
    title: 'Personal style / self-expression',
    description: 'Reflect for 10 minutes on what has helped or harmed this area recently.',
    impact: 93,
    category: 'ideal-gap',
  },
  {
    id: 'creativity-personal-style-self-expression-s9',
    factorId: 'creativity-personal-style-self-expression',
    title: 'Personal style / self-expression',
    description: 'Set a realistic improvement goal for the next month.',
    impact: 77,
    category: 'ideal-gap',
  },
  {
    id: 'creativity-personal-style-self-expression-s10',
    factorId: 'creativity-personal-style-self-expression',
    title: 'Personal style / self-expression',
    description: 'Experiment with one new approach or routine related to this factor.',
    impact: 72,
    category: 'ideal-gap',
  },
  {
    id: 'creativity-sharing-ideas-s1',
    factorId: 'creativity-sharing-ideas',
    title: 'Sharing ideas',
    description: 'Schedule a dedicated 30-minute block this week focused on this area.',
    impact: 93,
    category: 'ideal-gap',
  },
  {
    id: 'creativity-sharing-ideas-s2',
    factorId: 'creativity-sharing-ideas',
    title: 'Sharing ideas',
    description: 'Have a meaningful conversation with someone connected to this area.',
    impact: 89,
    category: 'ideal-gap',
  },
  {
    id: 'creativity-sharing-ideas-s3',
    factorId: 'creativity-sharing-ideas',
    title: 'Sharing ideas',
    description: 'Remove one friction point that makes this area harder than it should be.',
    impact: 86,
    category: 'ideal-gap',
  },
  {
    id: 'creativity-sharing-ideas-s4',
    factorId: 'creativity-sharing-ideas',
    title: 'Sharing ideas',
    description: 'Create a simple weekly habit that supports this factor.',
    impact: 73,
    category: 'ideal-gap',
  },
  {
    id: 'creativity-sharing-ideas-s5',
    factorId: 'creativity-sharing-ideas',
    title: 'Sharing ideas',
    description: 'Track your progress for the next 7 days.',
    impact: 90,
    category: 'ideal-gap',
  },
  {
    id: 'creativity-sharing-ideas-s6',
    factorId: 'creativity-sharing-ideas',
    title: 'Sharing ideas',
    description: 'Spend 20 minutes learning something new related to this area.',
    impact: 92,
    category: 'ideal-gap',
  },
  {
    id: 'creativity-sharing-ideas-s7',
    factorId: 'creativity-sharing-ideas',
    title: 'Sharing ideas',
    description: 'Plan a small activity this weekend that improves this factor.',
    impact: 77,
    category: 'ideal-gap',
  },
  {
    id: 'creativity-sharing-ideas-s8',
    factorId: 'creativity-sharing-ideas',
    title: 'Sharing ideas',
    description: 'Reflect for 10 minutes on what has helped or harmed this area recently.',
    impact: 78,
    category: 'ideal-gap',
  },
  {
    id: 'creativity-sharing-ideas-s9',
    factorId: 'creativity-sharing-ideas',
    title: 'Sharing ideas',
    description: 'Set a realistic improvement goal for the next month.',
    impact: 93,
    category: 'ideal-gap',
  },
  {
    id: 'creativity-sharing-ideas-s10',
    factorId: 'creativity-sharing-ideas',
    title: 'Sharing ideas',
    description: 'Experiment with one new approach or routine related to this factor.',
    impact: 83,
    category: 'ideal-gap',
  },
]

export const SUGGESTIONS_BY_FACTOR = SUGGESTION_POOL.reduce<Record<string, Suggestion[]>>(
  (acc, suggestion) => {
    const list = acc[suggestion.factorId] ?? []
    list.push(suggestion)
    acc[suggestion.factorId] = list
    return acc
  },
  {},
)
